/* test_ops.c - fixture-driven validation of the individual Kimi K3 kernels.
 *
 * Each fixture under tests/fixtures/ops/ is generated by tools/emit_fixtures.py from the
 * pure-torch reference and carries its own weights, inputs and expected outputs. This
 * binary reads them and reports pass or fail per operation.
 *
 * Per-op fixtures exist alongside the full-model oracle because the oracle localises
 * nothing: it reports that the stack is wrong, not which of ~40 kernels is responsible.
 * Every kernel is gated here individually so a failure names its own cause.
 *
 * Fixtures are parsed with the vendored json.h (Apache 2.0, see NOTICE).
 */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifndef _WIN32
#include <signal.h>            /* SIGABRT: the row-selection check, t_matmul_rows */
#include <sys/wait.h>
#include <unistd.h>
#endif

#include "json.h"
#include "k3.h"

/* FALLBACKS ONLY. The authority is the tolerance block in MANIFEST.json, loaded by main
 * and applied to every comparison. These values are used only if the manifest cannot be
 * read, and they are deliberately looser than the published contract so that the
 * fallback can never be mistaken for a pass at the real tolerance.
 *
 * Tolerances live in the manifest rather than in this file so the fixture set and its
 * pass criteria cannot drift apart. A harness that grades itself more kindly than its
 * own manifest is worse than no manifest at all. */
static float ATOL = 1e-4f;
static float RTOL = 1e-3f;

static int g_pass = 0, g_fail = 0;
/* Skips are counted and surfaced in the summary. A test whose fixture is absent prints
 * returned without touching either counter, so the summary still read "21 passed, 0
 * failed" with a test silently missing. For t_mxfp4 that meant the ONLY check of the
 * expert quantisation format against released checkpoint bytes could vanish and the suite
 * would still report a clean sweep. Skips are now counted and are a non-zero exit. */
static int g_skip = 0;

/* ------------------------------------------------------------- utilities ---- */
static char *slurp(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "cannot open %s\n", path); return NULL; }
    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
    char *b = (char *)malloc((size_t)n + 1);
    if (!b) { fclose(f); return NULL; }
    if (fread(b, 1, (size_t)n, f) != (size_t)n) { free(b); fclose(f); return NULL; }
    b[n] = 0; fclose(f);
    return b;
}

/* like slurp but silent, for optional fixtures whose absence is not an error */
static char *slurp_quiet(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
    char *b = (char *)malloc((size_t)n + 1);
    if (!b || fread(b, 1, (size_t)n, f) != (size_t)n) { free(b); fclose(f); return NULL; }
    b[n] = 0; fclose(f);
    return b;
}

/* pull "key": {"shape": [...], "data": [...]} into a freshly allocated float array */
static float *arr(jval *root, const char *key, int *count)
{
    jval *o = json_get(root, key);
    if (!o) { fprintf(stderr, "  missing key %s\n", key); return NULL; }
    jval *d = (o->t == J_OBJ) ? json_get(o, "data") : o;
    if (!d || d->t != J_ARR) { fprintf(stderr, "  key %s has no data array\n", key); return NULL; }
    float *v = (float *)malloc((size_t)d->len * sizeof(float));
    if (!v) return NULL;
    for (int i = 0; i < d->len; i++) v[i] = (float)d->kids[i]->num;
    if (count) *count = d->len;
    return v;
}

static double num(jval *root, const char *key, double dflt)
{
    jval *v = json_get(root, key);
    return (v && v->t == J_NUM) ? v->num : dflt;
}

/* JSON booleans are J_BOOL, not J_NUM. Reading one with num() silently yields the
 * default, which is how layer_mla was first mistaken for a KDA layer and asked for
 * weights it does not have. */
static int boolean(jval *root, const char *key, int dflt)
{
    jval *v = json_get(root, key);
    if (!v) return dflt;
    if (v->t == J_BOOL) return v->boolean;
    if (v->t == J_NUM)  return (int)v->num;
    return dflt;
}

/* read "key": {"shape": [...]} into dims[]; returns the rank, or 0 if absent.
 * Guessing row counts from element totals is how the first version of this file
 * went wrong; the fixtures carry the shape, so use it. */
static int shape(jval *root, const char *key, int *dims, int maxd)
{
    jval *o = json_get(root, key);
    if (!o || o->t != J_OBJ) return 0;
    jval *s = json_get(o, "shape");
    if (!s || s->t != J_ARR) return 0;
    const int r = s->len < maxd ? s->len : maxd;
    for (int i = 0; i < r; i++) dims[i] = (int)s->kids[i]->num;
    return r;
}

static void report(const char *name, const float *got, const float *want, int n)
{
    double worst = 0.0; int at = -1;
    for (int i = 0; i < n; i++) {
        const double a = fabs((double)got[i] - (double)want[i]);
        const double tol = ATOL + RTOL * fabs((double)want[i]);
        if (a / tol > worst) { worst = a / tol; at = i; }
    }
    if (worst <= 1.0) {
        printf("  PASS  %-14s n=%-6d worst=%.2fx tol\n", name, n, worst);
        g_pass++;
    } else {
        printf("  FAIL  %-14s n=%-6d worst=%.2fx tol at i=%d  got %.7f want %.7f\n",
               name, n, worst, at, got[at], want[at]);
        g_fail++;
    }
}

/* ----------------------------------------------------------------- tests ---- */
static void t_rmsnorm(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/rmsnorm.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int nw, ni, no;
    float *w = arr(r, "weight", &nw), *x = arr(r, "in", &ni), *e = arr(r, "out", &no);
    const float eps = (float)num(r, "eps", 1e-5);
    if (w && x && e) {
        const int rows = ni / nw;
        float *y = (float *)malloc((size_t)ni * sizeof(float));
        for (int i = 0; i < rows; i++) k3_rmsnorm(y + i * nw, x + i * nw, w, nw, eps);
        report("rmsnorm", y, e, no);
        free(y);
    }
    free(w); free(x); free(e); free(txt); free(ar);
}

static void t_situ(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/situ_glu.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int ni, no;
    float *x = arr(r, "in", &ni), *e = arr(r, "out", &no);
    const float b1 = (float)num(r, "beta", 4.0), b2 = (float)num(r, "linear_beta", 25.0);
    int din[4] = {0}, dout[4] = {0};
    const int rin = shape(r, "in", din, 4), rout = shape(r, "out", dout, 4);
    if (x && e && rin == 2 && rout == 2) {
        const int R = dout[0];        /* rows                              */
        const int W = dout[1];        /* output width; input row is 2*W    */
        if (din[1] != 2 * W || din[0] != R) {
            printf("  FAIL  situ_glu       shape mismatch: in=[%d,%d] out=[%d,%d], "
                   "expected in=[%d,%d]\n", din[0], din[1], R, W, R, 2 * W);
            g_fail++;
            free(x); free(e); free(txt); free(ar);
            return;
        }
        float *y = (float *)malloc((size_t)no * sizeof(float));
        for (int i = 0; i < R; i++)
            k3_situ_glu(y + i * W, x + i * 2 * W, W, b1, b2);
        report("situ_glu", y, e, no);
        /* The soft cap is the one property SiTU-GLU guarantees: |out| <= b1*b2, for any
         * input whatsoever. Violating it means a tanh was dropped or applied to the
         * wrong operand, so this counts as a failure rather than printing a warning
         * nothing acts on. */
        float mx = 0.f; for (int i = 0; i < no; i++) if (fabsf(y[i]) > mx) mx = fabsf(y[i]);
        const int bound_ok = (mx <= b1 * b2 + 1e-2f);
        printf("        bound check |out|=%.3f must be <= b1*b2=%.1f : %s\n",
               mx, b1 * b2, bound_ok ? "ok" : "VIOLATED");
        if (!bound_ok) {
            printf("        SiTU-GLU's soft cap does not hold, a tanh is missing or "
                   "applied to the wrong operand\n");
            g_fail++;
        }
        free(y);
    }
    free(x); free(e); free(txt); free(ar);
}

static void t_shortconv(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/shortconv.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int nw, ni, no, ns;
    float *w = arr(r, "weight", &nw), *x = arr(r, "in", &ni), *e = arr(r, "out", &no);
    float *st = arr(r, "state_after", &ns);
    int nxi, nxo;
    float *xn = arr(r, "in_next", &nxi), *en = arr(r, "out_next", &nxo);
    const int K = (int)num(r, "kernel", 4), C = (int)num(r, "channels", 0);
    if (w && x && e && C) {
        const int T = ni / C;
        float *y = (float *)malloc((size_t)ni * sizeof(float));
        float *s = (float *)calloc((size_t)C * (K - 1), sizeof(float));
        k3_shortconv(y, x, w, s, C, K, T);
        report("shortconv", y, e, no);
        if (st) report("conv_state", s, st, ns);

        /* CONTINUATION. Both checks above start from a zero state, so they say nothing
         * about whether k3_shortconv READS the state it was handed. A version that wrote
         * state_after correctly but ignored the incoming history passed all of them, and
         * would then be wrong for every decode step after the first. The fixture has
         * carried this continuation pair all along and no test used it: feed the state
         * from the first call straight into a second call over in_next, and require
         * out_next. This is the only check in the suite that can see the read side. */
        if (xn && en) {
            const int T2 = nxi / C;
            float *y2 = (float *)malloc((size_t)nxi * sizeof(float));
            k3_shortconv(y2, xn, w, s, C, K, T2);   /* s carries forward, deliberately */
            report("conv_continuation", y2, en, nxo);
            free(y2);
        } else {
            printf("  FAIL  conv_continuation  fixture lacks in_next/out_next\n");
            g_fail++;
        }
        free(y); free(s);
    }
    free(w); free(x); free(e); free(st); free(xn); free(en); free(txt); free(ar);
}

static void t_decay(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/kda_decay.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int na, nb, ng, nal, nz;
    float *A = arr(r, "A_log", &na), *dt = arr(r, "dt_bias", &nb);
    float *eg = arr(r, "g", &ng), *ea = arr(r, "alpha", &nal);
    float *z  = arr(r, "z", &nz);
    const float lb = (float)num(r, "lower_bound", -5.0);
    /* Drive the engine's own decay kernel and compare its output to torch elementwise.
     *
     * The weaker test this replaces only checked that the fixture's g values lay inside
     * (e^lb, 1]. That is a statement about the FIXTURE, not about the C: a k3_kda_decay
     * indexing A_log per channel instead of per head, or ignoring dt_bias entirely,
     * satisfies the range check. Exporting z lets the real function run forward from the
     * same inputs, which is the only version of this test that can fail. */
    if (A && dt && eg && ea && z) {
        const int H = na, D = nb / na, tok = ng / nb;
        float *gc = (float *)malloc((size_t)ng * sizeof(float));
        float *ac = (float *)malloc((size_t)nal * sizeof(float));
        double wg = 0.0, wa = 0.0;
        for (int t = 0; t < tok; t++)
            k3_kda_decay(gc + (size_t)t * nb, ac + (size_t)t * nb,
                         z + (size_t)t * nb, A, dt, H, D, lb);
        for (int i = 0; i < ng; i++) {
            const double dg = fabs((double)gc[i] - eg[i]);
            const double da = fabs((double)ac[i] - ea[i]);
            if (dg > wg) wg = dg;
            if (da > wa) wa = da;
        }
        /* A_log spans linspace(-0.4, 1.2) across heads, so a per-CHANNEL misindex moves
         * every element and shows up here immediately. */
        const int ok = (wg <= 1e-5) && (wa <= 1e-5);
        printf("  %s  kda_decay      H=%d D=%d tok=%d  max|dg|=%.3e max|dalpha|=%.3e "
               "(drives k3_kda_decay)\n", ok ? "PASS" : "FAIL", H, D, tok, wg, wa);
        if (ok) g_pass++; else g_fail++;
        free(gc); free(ac);
    } else {
        printf("  FAIL  kda_decay      fixture missing a required field%s\n",
               z ? "" : " (z absent: regenerate with tools/emit_fixtures.py)");
        g_fail++;
    }
    free(A); free(dt); free(eg); free(ea); free(z); free(txt); free(ar);
}

static void t_attnres(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/attnres.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int npx, nbr, nf, no;
    float *px = arr(r, "prefix_sum", &npx), *br = arr(r, "block_residual", &nbr);
    float *fold = arr(r, "fold_hint", &nf), *e = arr(r, "out", &no);
    const float eps = (float)num(r, "eps", 1e-5);
    if (px && br && fold && e) {
        const int n = nf, rows = npx / n, nblk = nbr / (rows * n);
        const int nsrc = nblk + 1;
        float *src = (float *)malloc((size_t)nsrc * n * sizeof(float));
        float *y = (float *)malloc((size_t)rows * n * sizeof(float));
        for (int rw = 0; rw < rows; rw++) {
            for (int b = 0; b < nblk; b++)
                memcpy(src + (size_t)b * n,
                       br + ((size_t)rw * nblk + b) * n, (size_t)n * sizeof(float));
            memcpy(src + (size_t)nblk * n, px + (size_t)rw * n, (size_t)n * sizeof(float));
            k3_attn_res(y + (size_t)rw * n, src, fold, nsrc, n, eps);
        }
        report("attn_res", y, e, no);
        free(src); free(y);
    }
    free(px); free(br); free(fold); free(e); free(txt); free(ar);
}

/* The isolated recurrence. This is where the ordering bug lives: decay, then the
 * rank-one delta write, then read the ALREADY UPDATED state. Any permutation runs
 * cleanly and produces a wrong model, so it gets its own test at T=1 and T=8. */
static void t_recur(const char *dir, const char *file)
{
    char p[512]; snprintf(p, sizeof(p), "%s/%s.json", dir, file);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    const int T = (int)num(r, "T", 0), H = (int)num(r, "H", 0);
    const int dk = (int)num(r, "d_k", 0), dv = (int)num(r, "d_v", dk);
    const float qs = (float)num(r, "q_scale", 1.0);
    int nq, nk, nv, na, nb, no, nso;
    float *q = arr(r, "q", &nq), *k = arr(r, "k", &nk), *v = arr(r, "v", &nv);
    float *al = arr(r, "alpha", &na), *bt = arr(r, "beta", &nb);
    float *eo = arr(r, "out", &no), *es = arr(r, "state_out", &nso);

    if (q && k && v && al && bt && eo && es && T && H && dk) {
        float *S = (float *)calloc((size_t)H * dk * dv, sizeof(float));
        float *out = (float *)malloc((size_t)T * H * dv * sizeof(float));
        float *qs_ = (float *)malloc((size_t)dk * sizeof(float));
        for (int t = 0; t < T; t++) {
            for (int h = 0; h < H; h++) {
                const size_t off = ((size_t)t * H + h) * dk;
                for (int i = 0; i < dk; i++) qs_[i] = q[off + i] * qs;   /* d_k^-0.5 */
                k3_kda_step(S + (size_t)h * dk * dv,
                            out + ((size_t)t * H + h) * dv,
                            qs_, k + off, v + off,
                            al + ((size_t)t * H + h) * dk,
                            bt[(size_t)t * H + h], dk, dv);
            }
        }
        char nm[32]; snprintf(nm, sizeof(nm), "%s_out", file);
        report(nm, out, eo, no);
        snprintf(nm, sizeof(nm), "%s_state", file);
        report(nm, S, es, nso);
        free(S); free(out); free(qs_);
    }
    free(q); free(k); free(v); free(al); free(bt); free(eo); free(es);
    free(txt); free(ar);
}

/* The router as it was written before experts were interleaved: one expert at a time,
 * one double chain over i = 0..hidden-1. The R_RIGHT branch is kept verbatim as the
 * bitwise reference; the other two are WRONG orders, computed on the same data only to
 * prove that data can tell them from the right one (see router_matches_plain_form). */
enum { R_RIGHT, R_REVERSED, R_TWO_CHAINS, R_COUNT };
static const char *RNAME[R_COUNT] = { "right", "reversed chain", "even/odd chains" };

static void router_plain(int *idx, float *w, const float *x, const float *W,
                         const float *bias, int hidden, int n_experts, int topk,
                         int renorm, float routed_scale, int mut)
{
    float *score  = (float *)malloc((size_t)n_experts * sizeof(float));
    float *choice = (float *)malloc((size_t)n_experts * sizeof(float));
    if (!score || !choice) { free(score); free(choice); return; }
    for (int e = 0; e < n_experts; e++) {
        const float *row = W + (size_t)e * hidden;
        double acc = 0.0;
        if (mut == R_REVERSED) {
            for (int i = hidden - 1; i >= 0; i--) acc += (double)row[i] * (double)x[i];
        } else if (mut == R_TWO_CHAINS) {
            double a0 = 0.0, a1 = 0.0;
            for (int i = 0; i < hidden; i++) {
                if (i & 1) a1 += (double)row[i] * (double)x[i];
                else       a0 += (double)row[i] * (double)x[i];
            }
            acc = a0 + a1;
        } else {
            for (int i = 0; i < hidden; i++) acc += (double)row[i] * (double)x[i];
        }
        score[e]  = 1.0f / (1.0f + expf(-(float)acc));
        choice[e] = score[e] + (bias ? bias[e] : 0.0f);
    }
    for (int j = 0; j < topk; j++) {
        int best = -1; float bv = -INFINITY;
        for (int e = 0; e < n_experts; e++)
            if (choice[e] > bv) { bv = choice[e]; best = e; }
        if (best < 0) { idx[j] = 0; w[j] = 0.0f; continue; }
        idx[j] = best; w[j] = score[best]; choice[best] = -INFINITY;
    }
    if (renorm && topk > 1) {
        double s = 0.0;
        for (int j = 0; j < topk; j++) s += (double)w[j];
        const float inv = (float)(1.0 / (s + 1e-20));
        for (int j = 0; j < topk; j++) w[j] *= inv;
    }
    for (int j = 0; j < topk; j++) w[j] *= routed_scale;
    free(score); free(choice);
}

/* xorshift32, for the generated tests below that carry their own seed. */
static unsigned xs32(unsigned *s)
{
    *s ^= *s << 13; *s ^= *s >> 17; *s ^= *s << 5;
    return *s;
}

/* Uniform in [-a, a). */
static float xs_unit(unsigned *s, float a)
{
    return ((float)(xs32(s) >> 8) / 8388608.0f - 1.0f) * a;
}

/* Router inputs. ORDINARY: W in +-0.05, x in +-1, bias in +-0.01, the distribution a
 * router sees. CANCELLING, what makes a wrong summation order VISIBLE: each expert's row
 * also carries +2^40 and -2^40 on two of four slots shared by the matrix, where x holds
 * one value v. The exact logit is still just the ordinary terms, but in double every
 * ordinary term added while the +-2^40 partial sum is live is rounded to its grid of
 * 2^-12, and which terms those are, and what the running sum is at each rounding, is
 * fixed by the order of the chain. So a reordered or split chain moves the logit by
 * 3e-7 to 2.4e-4 (measured for a reversed chain over these shapes at the fixed seed;
 * other seeds of the same generator give shifts from below float spacing up to about
 * 1e-3, and logits a little above 5), where the float spacing of these logits is about
 * 5e-7 or finer, not by a last double bit that the narrowing to float erases; the
 * sigmoid carries it into the score. 2^40 and not larger: at 2^60 the grid is 256, every term that meets
 * the big sum is lost outright, and two wrong orders could lose the same terms and
 * agree. A float times a float is exact in double and the pair cancels exactly, so
 * nothing overflows and the exact logit is unchanged. */
static void router_fill(float *W, float *x, float *b, int E, int H, int cancel,
                        unsigned *s)
{
    for (size_t i = 0; i < (size_t)E * H; i++)
        W[i] = xs_unit(s, 0.05f);
    for (int i = 0; i < H; i++)
        x[i] = xs_unit(s, 1.0f);
    for (int e = 0; e < E; e++)
        b[e] = xs_unit(s, 0.01f);
    if (!cancel || H < 4) return;
    int big[4];
    for (int k = 0; k < 4; k++) {
        int dup;
        do {
            big[k] = (int)(xs32(s) % (unsigned)H);
            dup = 0;
            for (int m = 0; m < k; m++) if (big[m] == big[k]) dup = 1;
        } while (dup);
    }
    const float v = ((xs32(s) & 1u) ? -1.0f : 1.0f)
                  * (1.0f + (float)(xs32(s) & 0xFFu) / 256.0f);
    for (int k = 0; k < 4; k++) x[big[k]] = v;
    for (int e = 0; e < E; e++) {
        float *row = W + (size_t)e * H;
        for (int k = 0; k < 4; k++) row[big[k]] = 0.0f;
        const int p = (int)(xs32(s) % 4u);
        int q = (int)(xs32(s) % 3u);
        if (q >= p) q++;
        row[big[p]] =  1099511627776.0f;   /* +2^40 */
        row[big[q]] = -1099511627776.0f;   /* -2^40 */
    }
}

/* Every expert's score back in expert order: with topk == n_experts, renorm off and a
 * routed_scale of 1, w[j] IS score[idx[j]]. */
static void router_scores(float *sc, const int *idx, const float *w, int E)
{
    for (int j = 0; j < E; j++) sc[idx[j]] = w[j];
}

/* k3_router held BITWISE to router_plain, which it replaced, over expert counts that fill
 * whole blocks, leave a tail, or are smaller than one block, including the released
 * 896 x 7168. Two legs per shape:
 *
 *   ordinary data with the released settings (renorm, routed_scale, top-k), which is
 *   what the kernel sees; and cancelling data with topk == n_experts, renorm off and a
 *   routed_scale of 1, so every expert's score is compared, not only the top-k.
 *
 * The cancelling leg is what gives this teeth. On ordinary data a reordered double chain
 * does not reach the float logit: measured on this distribution at 896 x 7168 over 100
 * inputs, a reversed or an even/odd split chain changed the double in about 97% of the
 * 89,600 logits and the float logit, and so the score, in none. So every shape also computes two WRONG orders on the cancelling data
 * -- the chain reversed, and split into even and odd chains added at the end -- and each
 * must change the scores of at least one expert in every shape and of most experts
 * overall; if the data ever stops telling orders apart, this fails instead of passing
 * vacuously. The full-block and tail paths each have shapes of their own here. */
static int router_matches_plain_form(long teeth[R_COUNT], long *scored)
{
    const int shapes[][3] = {           /* n_experts, hidden, topk */
        {1, 33, 1}, {7, 64, 3}, {8, 130, 2}, {9, 257, 4}, {17, 1000, 16}, {896, 7168, 16}
    };
    const int nshape = (int)(sizeof shapes / sizeof *shapes);
    int ok = 1;
    unsigned s = 20260922u;
    for (int c = 0; c < nshape; c++) {
        const int E = shapes[c][0], H = shapes[c][1], K = shapes[c][2];
        float *W  = (float *)malloc((size_t)E * H * sizeof(float));
        float *x  = (float *)malloc((size_t)H * sizeof(float));
        float *b  = (float *)malloc((size_t)E * sizeof(float));
        int   *ia = (int *)malloc((size_t)E * sizeof(int));
        int   *ib = (int *)malloc((size_t)E * sizeof(int));
        float *wa = (float *)malloc((size_t)E * sizeof(float));
        float *wb = (float *)malloc((size_t)E * sizeof(float));
        float *sr = (float *)malloc((size_t)E * sizeof(float));
        float *sm = (float *)malloc((size_t)E * sizeof(float));
        if (!W || !x || !b || !ia || !ib || !wa || !wb || !sr || !sm) {
            free(W); free(x); free(b); free(ia); free(ib); free(wa); free(wb);
            free(sr); free(sm);
            return 0;
        }

        /* ordinary data, released settings */
        router_fill(W, x, b, E, H, 0, &s);
        router_plain(ia, wa, x, W, b, H, E, K, 1, 2.5f, R_RIGHT);
        k3_router(ib, wb, x, W, b, H, E, K, 1, 2.5f);
        if (memcmp(ia, ib, (size_t)K * sizeof(int)) != 0 ||
            memcmp(wa, wb, (size_t)K * sizeof(float)) != 0) {
            printf("        router blocked form differs at n_experts=%d hidden=%d "
                   "(ordinary data)\n", E, H);
            ok = 0;
        }

        /* cancelling data, every expert's score */
        router_fill(W, x, b, E, H, 1, &s);
        router_plain(ia, wa, x, W, b, H, E, E, 0, 1.0f, R_RIGHT);
        k3_router(ib, wb, x, W, b, H, E, E, 0, 1.0f);
        if (memcmp(ia, ib, (size_t)E * sizeof(int)) != 0 ||
            memcmp(wa, wb, (size_t)E * sizeof(float)) != 0) {
            printf("        router blocked form differs at n_experts=%d hidden=%d "
                   "(cancelling data)\n", E, H);
            ok = 0;
        }
        router_scores(sr, ia, wa, E);
        for (int m = R_REVERSED; m < R_COUNT; m++) {
            router_plain(ib, wb, x, W, b, H, E, E, 0, 1.0f, m);
            router_scores(sm, ib, wb, E);
            int differ = 0;
            for (int e = 0; e < E; e++)
                differ += memcmp(&sr[e], &sm[e], sizeof(float)) != 0;
            teeth[m] += differ;
            if (differ == 0) {
                printf("        cancelling data cannot see a %s at n_experts=%d "
                       "hidden=%d\n", RNAME[m], E, H);
                ok = 0;
            }
        }
        *scored += E;
        free(W); free(x); free(b); free(ia); free(ib); free(wa); free(wb);
        free(sr); free(sm);
    }
    for (int m = R_REVERSED; m < R_COUNT; m++) {
        if (2 * teeth[m] < *scored) {
            printf("        cancelling data sees a %s in only %ld of %ld scores\n",
                   RNAME[m], teeth[m], *scored);
            ok = 0;
        }
    }
    return ok;
}

/* Router. The fixture's frozen bias reorders the top-k in 5 of 6 rows, so an engine
 * that ignored e_score_correction_bias, or that gathered the weights from the BIASED
 * scores, fails here rather than silently degrading. Indices are compared as SETS
 * because the reference uses topk(sorted=False), whose order is unspecified. */
static void t_router(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/router.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    int nw, nb, ni, nidx, nwt;
    float *W = arr(r, "gate_weight", &nw), *bias = arr(r, "bias", &nb);
    float *x = arr(r, "in", &ni);
    float *eidx = arr(r, "topk_idx", &nidx), *ewt = arr(r, "topk_weight", &nwt);
    const int K = (int)num(r, "top_k", 0), E = (int)num(r, "n_experts", 0);

    if (W && bias && x && eidx && ewt && K && E) {
        const int hidden = nw / E, rows = ni / hidden;
        int   *gi = (int   *)malloc((size_t)K * sizeof(int));
        float *gw = (float *)malloc((size_t)K * sizeof(float));
        int set_ok = 1; double worst_w = 0.0;

        for (int rw = 0; rw < rows; rw++) {
            k3_router(gi, gw, x + (size_t)rw * hidden, W, bias, hidden, E, K, 1, 1.0f);

            /* compare index SETS */
            for (int a = 0; a < K; a++) {
                int found = 0;
                for (int b = 0; b < K; b++)
                    if ((int)eidx[(size_t)rw * K + b] == gi[a]) { found = 1; break; }
                if (!found) { set_ok = 0;
                    printf("        row %d: C picked expert %d, reference did not\n", rw, gi[a]); }
            }
            /* match weights by expert id, since order is unspecified */
            for (int a = 0; a < K; a++) {
                for (int b = 0; b < K; b++) {
                    if ((int)eidx[(size_t)rw * K + b] != gi[a]) continue;
                    const double d = fabs((double)gw[a] - (double)ewt[(size_t)rw * K + b]);
                    const double tol = ATOL + RTOL * fabs((double)ewt[(size_t)rw * K + b]);
                    if (d / tol > worst_w) worst_w = d / tol;
                }
            }
        }
        /* k3_router walks experts in interleaved blocks; the fixture's handful of experts
         * cannot tell that apart from a one-expert-at-a-time loop, and neither can a
         * tolerance. So the blocked kernel is also held BITWISE to the plain form it
         * replaced, on cancelling data that makes a wrong chain order change the scores
         * (see router_matches_plain_form).
         *
         * Mutants run against it, each FAILING: the full-block chain reversed, the tail
         * block's chain reversed, the full block summed as even and odd chains added at
         * the end, a block reading the wrong expert's row, a tail block that drops its
         * last expert, and an accumulator rounded to float per term. Before the
         * cancelling leg existed the three reorderings all PASSED. */
        long teeth[R_COUNT] = {0}, scored = 0;
        const int bit_ok = router_matches_plain_form(teeth, &scored);
        if (set_ok && worst_w <= 1.0 && bit_ok) {
            printf("  PASS  router         rows=%-4d k=%d  index sets match, "
                   "worst weight=%.2fx tol, blocked form bitwise\n", rows, K, worst_w);
            g_pass++;
        } else {
            printf("  FAIL  router         index_sets=%s worst weight=%.2fx tol "
                   "blocked=%s\n", set_ok ? "ok" : "MISMATCH", worst_w,
                   bit_ok ? "bitwise" : "DIFFERS");
            g_fail++;
        }
        printf("        wrong orders on cancelling data change: %s %ld/%ld, "
               "%s %ld/%ld scores\n", RNAME[R_REVERSED], teeth[R_REVERSED], scored,
               RNAME[R_TWO_CHAINS], teeth[R_TWO_CHAINS], scored);
        free(gi); free(gw);
    }
    free(W); free(bias); free(x); free(eidx); free(ewt); free(txt); free(ar);
}

/* Gated MLA. The fixture now ships all eight weight tensors, so this is genuinely
 * reproducible. Watch for: the 192-wide head (128 nope + 64 unrotated rope), the
 * scale over 192 not 128, the single-head k_rope broadcast, and the gate applied
 * BEFORE o_proj with no norm. */
static void t_mla(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/mla.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    K3Cfg c; memset(&c, 0, sizeof c);
    c.qk_nope = (int)num(r, "qk_nope", 0);
    c.qk_rope = (int)num(r, "qk_rope", 0);
    c.kv_lora = (int)num(r, "kv_lora", 0);
    c.q_lora  = (int)num(r, "q_lora", 0);
    c.v_head  = (int)num(r, "v_head", 0);
    c.n_heads = (int)num(r, "n_heads", 0);
    c.rms_eps = (float)num(r, "rms_eps", 1e-5);

    int n_in, n_out, dum;
    float *x  = arr(r, "in", &n_in);
    float *eo = arr(r, "out", &n_out);
    /* Zeroed: wdt selects fp32 versus bf16 dispatch, and stack garbage there sends
     * fp32 fixture arrays into k3_matmul_bf16. That fails nondeterministically and
     * looks like an arithmetic bug in MLA rather than an initialisation bug here. */
    K3MlaW w; memset(&w, 0, sizeof w);
    w.q_a      = arr(r, "q_a_proj_weight", &dum);
    w.q_a_norm = arr(r, "q_a_layernorm_weight", &dum);
    w.q_b      = arr(r, "q_b_proj_weight", &dum);
    w.kv_a     = arr(r, "kv_a_proj_with_mqa_weight", &dum);
    w.kv_a_norm= arr(r, "kv_a_layernorm_weight", &dum);
    w.kv_b     = arr(r, "kv_b_proj_weight", &dum);
    w.o        = arr(r, "o_proj_weight", &dum);
    w.g        = arr(r, "g_proj_weight", &dum);

    if (x && eo && w.q_a && w.q_b && w.kv_a && w.kv_b && w.o) {
        int din[4] = {0};
        shape(r, "in", din, 4);
        const int T = din[1];
        c.hidden = din[2];
        float *scratch = (float *)malloc(k3_mla_scratch(&c, T) * sizeof(float));
        float *y = (float *)malloc((size_t)T * c.hidden * sizeof(float));
        if (scratch && y) {
            k3_mla(y, x, &w, &c, T, scratch);
            report("mla", y, eo, n_out);
            printf("        H=%d qh=%d (nope %d + rope %d) v=%d kv_lora=%d scale=%.6f\n",
                   c.n_heads, c.qk_nope + c.qk_rope, c.qk_nope, c.qk_rope,
                   c.v_head, c.kv_lora, 1.0 / sqrt((double)(c.qk_nope + c.qk_rope)));
        }
        free(scratch); free(y);
    }
    free(x); free(eo);
    free((void *)w.q_a); free((void *)w.q_a_norm); free((void *)w.q_b);
    free((void *)w.kv_a); free((void *)w.kv_a_norm); free((void *)w.kv_b);
    free((void *)w.o); free((void *)w.g);
    free(txt); free(ar);
}

/* Stable LatentMoE. The fixture drives SiTU into its caps and uses a routing bias
 * that genuinely reorders the top-k, so a wrong ordering (norming per expert instead
 * of on the aggregate, weighting the shared expert, routing on the latent instead of
 * the full width) fails here rather than degrading quietly. */
static void t_moe(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/moe.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    K3Cfg c; memset(&c, 0, sizeof c);
    c.hidden       = (int)num(r, "hidden", 0);
    c.latent       = (int)num(r, "latent", 0);
    c.moe_inter    = (int)num(r, "moe_inter", 0);
    c.n_experts    = (int)num(r, "n_experts", 0);
    c.topk         = (int)num(r, "top_k", 0);
    c.n_shared     = (int)num(r, "n_shared", 0);
    c.routed_scale = (float)num(r, "routed_scale", 1.0);
    c.moe_renorm   = (int)num(r, "renorm", 1);
    c.latent_norm  = (int)num(r, "latent_norm", 1);
    c.rms_eps      = (float)num(r, "rms_eps", 1e-5);
    c.situ_b1      = (float)num(r, "situ_b1", 4.0);
    c.situ_b2      = (float)num(r, "situ_b2", 25.0);

    int n_in, n_out, d;
    float *x  = arr(r, "in", &n_in);
    float *eo = arr(r, "out", &n_out);

    /* Zeroed, not merely assigned field by field: K3MoeW carries an optional expert
     * SOURCE, and a garbage src on an uninitialised stack struct is called as a
     * function pointer. */
    K3MoeW w; memset(&w, 0, sizeof w);
    w.gate        = arr(r, "gate_weight", &d);
    w.bias        = arr(r, "e_score_correction_bias", &d);
    w.down        = arr(r, "down_weight", &d);
    w.up          = arr(r, "up_weight", &d);
    w.latent_norm = arr(r, "norm_weight", &d);
    w.sh1         = arr(r, "shared_w1_weight", &d);
    w.sh3         = arr(r, "shared_w3_weight", &d);
    w.sh2         = arr(r, "shared_w2_weight", &d);

    /* routed experts arrive as experts_N_wK_weight; pack them contiguously */
    const size_t per13 = (size_t)c.moe_inter * c.latent;
    const size_t per2  = (size_t)c.latent * c.moe_inter;
    float *W1 = (float *)malloc(per13 * c.n_experts * sizeof(float));
    float *W3 = (float *)malloc(per13 * c.n_experts * sizeof(float));
    float *W2 = (float *)malloc(per2  * c.n_experts * sizeof(float));
    int packed = 1;
    for (int e = 0; e < c.n_experts && packed; e++) {
        char k1[64], k3[64], k2[64];
        snprintf(k1, sizeof k1, "experts_%d_w1_weight", e);
        snprintf(k3, sizeof k3, "experts_%d_w3_weight", e);
        snprintf(k2, sizeof k2, "experts_%d_w2_weight", e);
        float *a1 = arr(r, k1, &d), *a3 = arr(r, k3, &d), *a2 = arr(r, k2, &d);
        if (!a1 || !a3 || !a2) { packed = 0; free(a1); free(a3); free(a2); break; }
        memcpy(W1 + e * per13, a1, per13 * sizeof(float));
        memcpy(W3 + e * per13, a3, per13 * sizeof(float));
        memcpy(W2 + e * per2,  a2, per2  * sizeof(float));
        free(a1); free(a3); free(a2);
    }
    w.w1 = W1; w.w3 = W3; w.w2 = W2;

    if (x && eo && packed && w.gate && w.down && w.up && w.sh1) {
        int din[4] = {0}; shape(r, "in", din, 4);
        const int T = din[1];
        int   *idx = (int   *)malloc((size_t)c.topk * sizeof(int));
        float *wt  = (float *)malloc((size_t)c.topk * sizeof(float));
        float *sc  = (float *)malloc(k3_moe_scratch(&c, T) * sizeof(float));
        float *y   = (float *)malloc((size_t)T * c.hidden * sizeof(float));
        if (idx && wt && sc && y) {
            k3_moe(y, x, &w, &c, T, idx, wt, sc);
            report("moe", y, eo, n_out);
            printf("        hidden=%d latent=%d inter=%d experts=%d top%d shared=%d\n",
                   c.hidden, c.latent, c.moe_inter, c.n_experts, c.topk, c.n_shared);
        }
        free(idx); free(wt); free(sc); free(y);
    } else if (!packed) {
        printf("  FAIL  moe            could not pack expert weights from fixture\n");
        g_fail++;
    }
    free(x); free(eo); free(W1); free(W3); free(W2);
    free((void *)w.gate); free((void *)w.bias); free((void *)w.down); free((void *)w.up);
    free((void *)w.latent_norm); free((void *)w.sh1); free((void *)w.sh3); free((void *)w.sh2);
    free(txt); free(ar);
}

/* A streamed expert source over experts held in memory as MXFP4, counting get() calls. */
typedef struct {
    K3ExpertSrc src;
    unsigned char *p13, *s13, *p2, *s2;   /* gate and up share a shape; down its own  */
    size_t pb13, sb13, pb2, sb2;          /* bytes per expert of each                 */
    long gets;
} MemExperts;

static int mem_get(K3ExpertSrc *self, int layer, int e, K3ExpertQ *q)
{
    MemExperts *m = (MemExperts *)self->ctx;
    (void)layer;
    m->gets++;
    q->p1 = m->p13 + (size_t)(2 * e) * m->pb13;
    q->s1 = m->s13 + (size_t)(2 * e) * m->sb13;
    q->p3 = m->p13 + (size_t)(2 * e + 1) * m->pb13;
    q->s3 = m->s13 + (size_t)(2 * e + 1) * m->sb13;
    q->p2 = m->p2  + (size_t)e * m->pb2;
    q->s2 = m->s2  + (size_t)e * m->sb2;
    return 0;
}

/* Orders in which a position's routed contributions can be summed: the top-k order k3_moe
 * uses, and two WRONG ones -- reversed, and the order the batched path fetches experts in
 * (first appearance in the 64-position sub-chunk), which is the natural mistake there. */
enum { S_RIGHT, S_REVERSED, S_FETCH, S_COUNT };
static const char *SNAME[S_COUNT] = { "top-k", "reversed", "fetch order" };

/* The MoE of k3_moe with a streamed source, written out with public ops, one position at
 * a time, summing each position's routed contributions in the order `mut` names. With
 * S_RIGHT it must match k3_moe bit for bit, which is what licenses using the other two as
 * the wrong orders the data has to be able to see. Every matrix here is fp32, so each
 * k3_matmul is the per-position form of the k3_mmw_batch the engine calls. */
static void moe_ref(float *out, const float *x, const K3MoeW *w, const K3Cfg *c, int T,
                    int chunk, int mut)
{
    const int E = c->hidden, L = c->latent, I = c->moe_inter, K = c->topk;
    const int SI = I * c->n_shared;
    float *z    = (float *)malloc((size_t)L * sizeof(float));
    float *acc  = (float *)malloc((size_t)L * sizeof(float));
    float *cb   = (float *)malloc((size_t)K * L * sizeof(float));
    float *gu   = (float *)malloc((size_t)2 * I * sizeof(float));
    float *sgu  = (float *)malloc((size_t)2 * SI * sizeof(float));
    float *sdn  = (float *)malloc((size_t)E * sizeof(float));
    float *wt   = (float *)malloc((size_t)T * K * sizeof(float));
    int   *idx  = (int *)malloc((size_t)T * K * sizeof(int));
    int   *rank = (int *)malloc((size_t)c->n_experts * sizeof(int));
    if (!z || !acc || !cb || !gu || !sgu || !sdn || !wt || !idx || !rank) {
        printf("        moe_ref: out of memory\n");
        exit(1);
    }
    for (int t = 0; t < T; t++)
        k3_router(idx + (size_t)t * K, wt + (size_t)t * K, x + (size_t)t * E, w->gate,
                  w->bias, E, c->n_experts, K, c->moe_renorm, c->routed_scale);
    for (int t = 0; t < T; t++) {
        const float *xt = x + (size_t)t * E;
        const int *it = idx + (size_t)t * K;
        const float *wtt = wt + (size_t)t * K;
        if (t % chunk == 0) {           /* first-appearance rank within the sub-chunk */
            int nu = 0;
            for (int e = 0; e < c->n_experts; e++) rank[e] = -1;
            for (int u = t; u < T && u < t + chunk; u++)
                for (int j = 0; j < K; j++)
                    if (rank[idx[(size_t)u * K + j]] < 0) rank[idx[(size_t)u * K + j]] = nu++;
        }
        k3_matmul(z, xt, (const float *)w->down, E, L);
        for (int j = 0; j < K; j++) {
            K3ExpertQ q;
            w->src->get(w->src, w->layer, it[j], &q);
            k3_matmul_mxfp4(gu,     z, q.p1, q.s1, L, I, K3_MXFP4_GROUP);
            k3_matmul_mxfp4(gu + I, z, q.p3, q.s3, L, I, K3_MXFP4_GROUP);
            k3_situ_glu(gu, gu, I, c->situ_b1, c->situ_b2);
            k3_matmul_mxfp4(cb + (size_t)j * L, gu, q.p2, q.s2, I, L, K3_MXFP4_GROUP);
        }
        int order[K3_MAX_TOPK];
        for (int j = 0; j < K; j++) order[j] = mut == S_REVERSED ? K - 1 - j : j;
        if (mut == S_FETCH)             /* slots by their expert's rank: insertion sort */
            for (int a = 1; a < K; a++)
                for (int b = a; b > 0 && rank[it[order[b]]] < rank[it[order[b - 1]]]; b--) {
                    const int tmp = order[b]; order[b] = order[b - 1]; order[b - 1] = tmp;
                }
        for (int i = 0; i < L; i++) acc[i] = 0.0f;
        for (int a = 0; a < K; a++) {
            const int j = order[a];
            for (int i = 0; i < L; i++) acc[i] += wtt[j] * cb[(size_t)j * L + i];
        }
        if (c->latent_norm) k3_rmsnorm(acc, acc, w->latent_norm, L, c->rms_eps);
        float *ot = out + (size_t)t * E;
        k3_matmul(ot, acc, (const float *)w->up, L, E);
        k3_matmul(sgu,      xt, (const float *)w->sh1, E, SI);
        k3_matmul(sgu + SI, xt, (const float *)w->sh3, E, SI);
        k3_situ_glu(sgu, sgu, SI, c->situ_b1, c->situ_b2);
        k3_matmul(sdn, sgu, (const float *)w->sh2, SI, E);
        for (int i = 0; i < E; i++) ot[i] += sdn[i];
    }
    free(z); free(acc); free(cb); free(gu); free(sgu); free(sdn); free(wt); free(idx);
    free(rank);
}

/* The batched prefill MoE, bitwise against the per-token k3_moe, at K3's top-16.
 *
 * k3_moe_prefill fetches each unique routed expert once per 64-position sub-chunk and
 * applies it to every (position, slot) that chose it; the hazard particular to it is
 * summing a position's contributions in that fetch order instead of the top-k order
 * k3_moe uses. Nothing else reaches it: the oracle and t_moe run resident experts
 * through k3_moe, and the CLI's 65/129/130-token gate runs the tiny checkpoint, which
 * routes to the top 2, where 0 + a + b and 0 + b + a are the same float in either order.
 * Here a position sums sixteen contributions, as on K3, over T = 130 positions (two full
 * sub-chunks and a remainder of two), with 40 experts so that every sub-chunk reuses
 * each expert many times.
 *
 * The data proves it can see the order: the same MoE written out with public ops must
 * match k3_moe bitwise when it sums in top-k order, and must DIFFER on most positions
 * when it sums reversed or in fetch order. The dedup itself is checked by count: one
 * get() per unique expert per sub-chunk, against T * 16 for the per-token path. */
static void t_moe_prefill(void)
{
    K3Cfg c; memset(&c, 0, sizeof c);
    c.hidden = 64; c.latent = 64; c.moe_inter = 64; c.n_experts = 40; c.topk = 16;
    c.n_shared = 1; c.routed_scale = 2.5f; c.moe_renorm = 1; c.latent_norm = 1;
    c.rms_eps = 1e-5f; c.situ_b1 = 4.0f; c.situ_b2 = 25.0f;
    const int T = 130, CHUNK = 64;
    const int E = c.hidden, L = c.latent, I = c.moe_inter, NE = c.n_experts, K = c.topk;
    const int SI = I * c.n_shared;

    unsigned s = 0x6D6F65u;
    float *x    = (float *)malloc((size_t)T * E * sizeof(float));
    float *gate = (float *)malloc((size_t)NE * E * sizeof(float));
    float *bias = (float *)malloc((size_t)NE * sizeof(float));
    float *down = (float *)malloc((size_t)L * E * sizeof(float));
    float *up   = (float *)malloc((size_t)E * L * sizeof(float));
    float *sh1  = (float *)malloc((size_t)SI * E * sizeof(float));
    float *sh3  = (float *)malloc((size_t)SI * E * sizeof(float));
    float *sh2  = (float *)malloc((size_t)E * SI * sizeof(float));
    float *lnw  = (float *)malloc((size_t)L * sizeof(float));
    MemExperts m; memset(&m, 0, sizeof m);
    m.pb13 = (size_t)I * (L / 2); m.sb13 = (size_t)I * ((L + 31) / 32);
    m.pb2  = (size_t)L * (I / 2); m.sb2  = (size_t)L * ((I + 31) / 32);
    m.p13 = (unsigned char *)malloc(2 * NE * m.pb13);
    m.s13 = (unsigned char *)malloc(2 * NE * m.sb13);
    m.p2  = (unsigned char *)malloc(NE * m.pb2);
    m.s2  = (unsigned char *)malloc(NE * m.sb2);
    const size_t nout = (size_t)T * E;
    float *yb = (float *)malloc(nout * sizeof(float));      /* k3_moe_prefill */
    float *yt = (float *)malloc(nout * sizeof(float));      /* k3_moe         */
    float *yr = (float *)malloc(nout * sizeof(float));      /* moe_ref        */
    float *sc = (float *)malloc(k3_moe_scratch(&c, T) * sizeof(float));
    int   *idx = (int *)malloc((size_t)K * sizeof(int));
    float *wt  = (float *)malloc((size_t)K * sizeof(float));
    if (!x || !gate || !bias || !down || !up || !sh1 || !sh3 || !sh2 || !lnw || !m.p13 ||
        !m.s13 || !m.p2 || !m.s2 || !yb || !yt || !yr || !sc || !idx || !wt) {
        printf("  FAIL  moe_prefill    out of memory\n");
        g_fail++;
        exit(1);
    }
    for (size_t i = 0; i < nout; i++) x[i] = xs_unit(&s, 1.0f);
    for (int i = 0; i < NE * E; i++) gate[i] = xs_unit(&s, 0.05f);
    for (int i = 0; i < NE; i++) bias[i] = xs_unit(&s, 0.01f);
    for (int i = 0; i < L * E; i++) down[i] = xs_unit(&s, 0.2f);
    for (int i = 0; i < E * L; i++) up[i] = xs_unit(&s, 0.2f);
    for (int i = 0; i < SI * E; i++) { sh1[i] = xs_unit(&s, 0.2f); sh3[i] = xs_unit(&s, 0.2f); }
    for (int i = 0; i < E * SI; i++) sh2[i] = xs_unit(&s, 0.2f);
    for (int i = 0; i < L; i++) lnw[i] = 1.0f + xs_unit(&s, 0.25f);
    /* random FP4 nibbles, and E8M0 scales 2^-6 .. 2^-3 (bytes 121..124) */
    for (size_t i = 0; i < 2 * NE * m.pb13; i++) m.p13[i] = (unsigned char)(xs32(&s) >> 8);
    for (size_t i = 0; i < NE * m.pb2; i++)      m.p2[i]  = (unsigned char)(xs32(&s) >> 8);
    for (size_t i = 0; i < 2 * NE * m.sb13; i++)
        m.s13[i] = (unsigned char)(121 + (xs32(&s) >> 8) % 4);
    for (size_t i = 0; i < NE * m.sb2; i++)
        m.s2[i]  = (unsigned char)(121 + (xs32(&s) >> 8) % 4);
    m.src.get = mem_get;                 /* getmany and resident stay NULL */
    m.src.ctx = &m;

    K3MoeW w; memset(&w, 0, sizeof w);
    w.gate = gate; w.bias = bias; w.latent_norm = lnw;
    w.down = down; w.up = up; w.sh1 = sh1; w.sh3 = sh3; w.sh2 = sh2; w.wdt = K3_WF32;
    w.src = &m.src; w.layer = 1;

    const long drops0 = k3_expert_drops;
    m.gets = 0;
    k3_moe(yt, x, &w, &c, T, idx, wt, sc);
    const long gets_token = m.gets;
    m.gets = 0;
    k3_moe_prefill(yb, x, &w, &c, T, idx, wt, sc);
    const long gets_batch = m.gets;

    /* unique experts per sub-chunk, from the router itself */
    long uniq = 0;
    {
        char  *seen = (char *)malloc((size_t)NE);
        int   *ri = (int *)malloc((size_t)K * sizeof(int));
        float *rw = (float *)malloc((size_t)K * sizeof(float));
        if (!seen || !ri || !rw) { printf("  FAIL  moe_prefill    out of memory\n"); exit(1); }
        for (int t0 = 0; t0 < T; t0 += CHUNK) {
            memset(seen, 0, (size_t)NE);
            for (int t = t0; t < T && t < t0 + CHUNK; t++) {
                k3_router(ri, rw, x + (size_t)t * E, gate, bias, E, NE, K,
                          c.moe_renorm, c.routed_scale);
                for (int j = 0; j < K; j++) if (!seen[ri[j]]) { seen[ri[j]] = 1; uniq++; }
            }
        }
        free(seen); free(ri); free(rw);
    }

    const int batch_ok = memcmp(yb, yt, nout * sizeof(float)) == 0;
    moe_ref(yr, x, &w, &c, T, CHUNK, S_RIGHT);
    const int ref_ok = memcmp(yr, yt, nout * sizeof(float)) == 0;
    int teeth[S_COUNT] = {0}, teeth_ok = 1;
    for (int mu = S_REVERSED; mu < S_COUNT; mu++) {
        float *ym = (float *)malloc(nout * sizeof(float));
        if (!ym) { printf("  FAIL  moe_prefill    out of memory\n"); exit(1); }
        moe_ref(ym, x, &w, &c, T, CHUNK, mu);
        for (int t = 0; t < T; t++)
            teeth[mu] += memcmp(ym + (size_t)t * E, yr + (size_t)t * E,
                                (size_t)E * sizeof(float)) != 0;
        if (2 * teeth[mu] < T) teeth_ok = 0;
        free(ym);
    }
    const int count_ok = gets_token == (long)T * K && gets_batch == uniq;
    const int drops_ok = k3_expert_drops == drops0;

    if (batch_ok && ref_ok && teeth_ok && count_ok && drops_ok) {
        printf("  PASS  moe_prefill    T=%d top%d of %d  bitwise == per-token k3_moe, "
               "%ld expert gets vs %ld\n", T, K, NE, gets_batch, gets_token);
        g_pass++;
    } else {
        printf("  FAIL  moe_prefill    batched=%s reference=%s gets=%ld/%ld (want %ld/%d) "
               "drops=%ld\n", batch_ok ? "bitwise" : "DIFFERS",
               ref_ok ? "bitwise" : "DIFFERS", gets_batch, gets_token, uniq, T * K,
               k3_expert_drops - drops0);
        g_fail++;
    }
    printf("        wrong routed-sum orders change: %s %d/%d, %s %d/%d positions\n",
           SNAME[S_REVERSED], teeth[S_REVERSED], T, SNAME[S_FETCH], teeth[S_FETCH], T);

    free(x); free(gate); free(bias); free(down); free(up); free(sh1); free(sh3); free(sh2);
    free(lnw); free(m.p13); free(m.s13); free(m.p2); free(m.s2);
    free(yb); free(yt); free(yr); free(sc); free(idx); free(wt);
}

/* The full KDA layer. This is the last and hardest component before the decoder
 * layer: projections, three depthwise convs with fused SiLU, L2Norm on q/k only,
 * the shared low-rank decay, the per-head beta, the recurrence, the head-wise norm
 * and the gate in THAT order, then the output projection. Run at T=1 (the decode
 * path) and T=8 (where an ordering bug compounds). */
static void t_kda_layer(const char *dir, const char *file)
{
    char p[512]; snprintf(p, sizeof(p), "%s/%s.json", dir, file);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    K3Cfg c; memset(&c, 0, sizeof c);
    c.kda_heads    = (int)num(r, "H", 0);
    c.kda_head_dim = (int)num(r, "d_k", 0);
    c.conv_k       = (int)num(r, "conv_k", 4);
    c.gate_lb      = (float)num(r, "lower_bound", -5.0);
    c.rms_eps      = (float)num(r, "rms_eps", 1e-5);

    int n_in, n_out, n_st, d;
    float *x  = arr(r, "in", &n_in);
    float *eo = arr(r, "out", &n_out);
    float *es = arr(r, "state_out", &n_st);

    K3KdaW w; memset(&w, 0, sizeof w);   /* see the note in t_mla: wdt must not be garbage */
    w.q = arr(r, "q_proj", &d);  w.k = arr(r, "k_proj", &d);  w.v = arr(r, "v_proj", &d);
    w.q_conv = arr(r, "q_conv", &d); w.k_conv = arr(r, "k_conv", &d);
    w.v_conv = arr(r, "v_conv", &d);
    w.f_a = arr(r, "f_a", &d);   w.f_b = arr(r, "f_b", &d);
    w.A_log = arr(r, "A_log", &d); w.dt_bias = arr(r, "dt_bias", &d);
    w.b = arr(r, "b_proj", &d);  w.g = arr(r, "g_proj", &d);
    w.o_norm = arr(r, "o_norm", &d); w.o = arr(r, "o_proj", &d);

    if (x && eo && w.q && w.f_b && w.A_log && w.o) {
        int din[4] = {0}; shape(r, "in", din, 4);
        const int T = din[1];
        c.hidden = din[2];
        const int P = c.kda_heads * c.kda_head_dim, hist = c.conv_k - 1;
        float *st = (float *)calloc((size_t)P * c.kda_head_dim
                                    + (size_t)3 * P * hist, sizeof(float));
        float *sc = (float *)malloc(k3_kda_scratch(&c, T) * sizeof(float));
        float *y  = (float *)malloc((size_t)T * c.hidden * sizeof(float));
        if (st && sc && y) {
            k3_kda_layer(y, x, &w, &c, T, st, sc);
            char nm[40]; snprintf(nm, sizeof nm, "%s_out", file);
            report(nm, y, eo, n_out);
            if (es) { snprintf(nm, sizeof nm, "%s_state", file);
                      report(nm, st, es, n_st); }
        }
        free(st); free(sc); free(y);
    }
    free(x); free(eo); free(es);
    free((void*)w.q); free((void*)w.k); free((void*)w.v);
    free((void*)w.q_conv); free((void*)w.k_conv); free((void*)w.v_conv);
    free((void*)w.f_a); free((void*)w.f_b); free((void*)w.A_log);
    free((void*)w.dt_bias); free((void*)w.b); free((void*)w.g);
    free((void*)w.o_norm); free((void*)w.o);
    free(txt); free(ar);
}

/* A whole decoder layer: the AttnRes wiring plus attention plus the MoE. This is the
 * last stop before the full model. What it actually exercises that nothing else does:
 * the aggregate REPLACING the layer input, the snapshot push, and the prefix_sum
 * reset at a block boundary. layer_kda is index 1 (not a boundary, so the running
 * residual survives); layer_mla is index 3 (also not a boundary here, block size 3
 * means boundaries are 0,3,6,9,12 -- so index 3 IS one). Between them both paths run. */
static float *pack_experts(jval *r, const char *fmt, int n, size_t per)
{
    float *W = (float *)malloc(per * n * sizeof(float));
    if (!W) return NULL;
    for (int e = 0; e < n; e++) {
        char key[80]; int d;
        snprintf(key, sizeof key, fmt, e);
        float *a = arr(r, key, &d);
        if (!a) { free(W); return NULL; }
        memcpy(W + (size_t)e * per, a, per * sizeof(float));
        free(a);
    }
    return W;
}

static void t_layer(const char *dir, const char *file)
{
    char p[512]; snprintf(p, sizeof(p), "%s/%s.json", dir, file);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    const int li = (int)num(r, "layer_idx", 0);
    const int is_mla = boolean(r, "is_mla", 0);

    K3Cfg c; memset(&c, 0, sizeof c);
    c.hidden = (int)num(r, "hidden", 0);
    c.rms_eps = (float)num(r, "rms_eps", 1e-5);
    c.attn_res_block = (int)num(r, "attn_res_block_size", 3);
    c.n_layers = 13;
    c.kda_heads = 4; c.kda_head_dim = 16; c.conv_k = 4; c.gate_lb = -5.0f;
    c.n_heads = 4; c.q_lora = 64; c.kv_lora = 32;
    c.qk_nope = 24; c.qk_rope = 8; c.v_head = 16;
    c.n_experts = 8; c.topk = 2; c.n_shared = 2;
    c.latent = 64; c.moe_inter = 48; c.routed_scale = 1.0f;
    c.moe_renorm = 1; c.latent_norm = 1;
    c.situ_b1 = 4.0f; c.situ_b2 = 25.0f;
    c.first_dense = 1; c.dense_inter = 96;

    int n_in, n_out, n_bri, d;
    float *x   = arr(r, "in", &n_in);
    float *eo  = arr(r, "out", &n_out);
    float *bri = arr(r, "block_residual_in", &n_bri);

    K3KdaW kw; K3MlaW mw; K3MoeW ow; K3LayerW lw;
    memset(&kw, 0, sizeof kw); memset(&mw, 0, sizeof mw);
    memset(&ow, 0, sizeof ow); memset(&lw, 0, sizeof lw);
    lw.in_norm       = arr(r, "input_layernorm_weight", &d);
    lw.post_norm     = arr(r, "post_attention_layernorm_weight", &d);
    lw.attn_res_norm = arr(r, "self_attention_res_norm_weight", &d);
    lw.attn_res_proj = arr(r, "self_attention_res_proj_weight", &d);
    lw.mlp_res_norm  = arr(r, "mlp_res_norm_weight", &d);
    lw.mlp_res_proj  = arr(r, "mlp_res_proj_weight", &d);

    if (is_mla) {
        mw.q_a = arr(r,"self_attn_q_a_proj_weight",&d);
        mw.q_a_norm = arr(r,"self_attn_q_a_layernorm_weight",&d);
        mw.q_b = arr(r,"self_attn_q_b_proj_weight",&d);
        mw.kv_a = arr(r,"self_attn_kv_a_proj_with_mqa_weight",&d);
        mw.kv_a_norm = arr(r,"self_attn_kv_a_layernorm_weight",&d);
        mw.kv_b = arr(r,"self_attn_kv_b_proj_weight",&d);
        mw.o = arr(r,"self_attn_o_proj_weight",&d);
        mw.g = arr(r,"self_attn_g_proj_weight",&d);
        lw.mla = &mw;
    } else {
        kw.q = arr(r,"self_attn_q_proj_weight",&d);
        kw.k = arr(r,"self_attn_k_proj_weight",&d);
        kw.v = arr(r,"self_attn_v_proj_weight",&d);
        kw.q_conv = arr(r,"self_attn_q_conv1d_weight",&d);
        kw.k_conv = arr(r,"self_attn_k_conv1d_weight",&d);
        kw.v_conv = arr(r,"self_attn_v_conv1d_weight",&d);
        kw.f_a = arr(r,"self_attn_f_a_proj_weight",&d);
        kw.f_b = arr(r,"self_attn_f_b_proj_weight",&d);
        kw.A_log = arr(r,"self_attn_A_log",&d);
        kw.dt_bias = arr(r,"self_attn_dt_bias",&d);
        kw.b = arr(r,"self_attn_b_proj_weight",&d);
        kw.g = arr(r,"self_attn_g_proj_weight",&d);
        kw.o_norm = arr(r,"self_attn_o_norm_weight",&d);
        kw.o = arr(r,"self_attn_o_proj_weight",&d);
        lw.kda = &kw;
    }

    ow.gate = arr(r,"mlp_gate_weight",&d);
    ow.bias = arr(r,"mlp_e_score_correction_bias",&d);
    ow.down = arr(r,"mlp_down_weight",&d);
    ow.up   = arr(r,"mlp_up_weight",&d);
    ow.latent_norm = arr(r,"mlp_norm_weight",&d);
    ow.sh1 = arr(r,"mlp_shared_w1_weight",&d);
    ow.sh3 = arr(r,"mlp_shared_w3_weight",&d);
    ow.sh2 = arr(r,"mlp_shared_w2_weight",&d);
    ow.w1 = pack_experts(r,"mlp_experts_%d_w1_weight",c.n_experts,(size_t)c.moe_inter*c.latent);
    ow.w3 = pack_experts(r,"mlp_experts_%d_w3_weight",c.n_experts,(size_t)c.moe_inter*c.latent);
    ow.w2 = pack_experts(r,"mlp_experts_%d_w2_weight",c.n_experts,(size_t)c.latent*c.moe_inter);
    lw.moe = &ow;

    if (x && eo && bri && ow.w1 && ow.w2 && ow.w3 && lw.in_norm) {
        int din[4]={0}, dbr[4]={0};
        shape(r,"in",din,4); shape(r,"block_residual_in",dbr,4);
        const int T = din[1], nb_in = dbr[1];
        const int maxb = c.n_layers / c.attn_res_block + 2;

        float *h  = (float*)malloc((size_t)T*c.hidden*sizeof(float));
        float *br = (float*)calloc((size_t)T*maxb*c.hidden,sizeof(float));
        float *sc = (float*)malloc(k3_layer_scratch(&c,T)*sizeof(float));
        const int P = c.kda_heads*c.kda_head_dim;
        float *st = (float*)calloc((size_t)P*c.kda_head_dim + (size_t)3*P*(c.conv_k-1),
                                   sizeof(float));
        int nb = nb_in;
        if (h && br && sc && st) {
            memcpy(h, x, (size_t)T*c.hidden*sizeof(float));
            for (int t=0;t<T;t++)
                for (int b=0;b<nb_in;b++)
                    memcpy(br+((size_t)t*maxb+b)*c.hidden,
                           bri+((size_t)t*nb_in+b)*c.hidden,
                           (size_t)c.hidden*sizeof(float));
            k3_decoder_layer(h, br, &nb, &lw, &c, li, T, st, sc);
            char nm[40]; snprintf(nm,sizeof nm,"%s",file);
            report(nm, h, eo, n_out);
            printf("        layer %d (%s), blocks %d -> %d, boundary=%s\n",
                   li, is_mla?"MLA":"KDA", nb_in, nb,
                   (li % c.attn_res_block==0)?"YES, prefix_sum cleared":"no");
        }
        free(h); free(br); free(sc); free(st);
    }
    free(x); free(eo); free(bri);
    free((void*)ow.w1); free((void*)ow.w3); free((void*)ow.w2);
    free(txt); free(ar);
}

/* MXFP4 dequant, checked against REAL Kimi K3 checkpoint bytes. Every other fixture
 * uses synthetic values; this one cannot, because the point is to agree with how
 * Moonshot actually wrote the bytes. */
static void t_mxfp4(const char *dir)
{
    /* mxfp4.json sits BESIDE the ops/ directory, not inside it, because it is built
     * from released checkpoint bytes rather than from the reference implementation.
     * Both orderings are attempted. */
    char p[512];
    snprintf(p, sizeof(p), "%s/mxfp4.json", dir);
    char *txt = slurp_quiet(p);
    if (!txt) { snprintf(p, sizeof(p), "%s/../mxfp4.json", dir); txt = slurp_quiet(p); }
    if (!txt) {
        printf("  SKIP  mxfp4          fixture absent; run tools/fetch_mxfp4.py\n");
        g_skip++;
        return;
    }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    const int rows  = (int)num(r, "rows", 0);
    const int pcols = (int)num(r, "packed_cols", 0);
    const int grp   = (int)num(r, "group_size", 32);
    int np_, ns_, ne_;
    float *pf = arr(r, "packed", &np_);
    float *sf = arr(r, "scales", &ns_);
    float *ef = arr(r, "expected", &ne_);

    if (pf && sf && ef && rows && pcols) {
        unsigned char *P = (unsigned char *)malloc((size_t)np_);
        unsigned char *S = (unsigned char *)malloc((size_t)ns_);
        float *y = (float *)malloc((size_t)ne_ * sizeof(float));
        for (int i = 0; i < np_; i++) P[i] = (unsigned char)pf[i];
        for (int i = 0; i < ns_; i++) S[i] = (unsigned char)sf[i];

        k3_mxfp4_dequant(y, P, S, rows, pcols, grp);

        /* exact equality: dequantisation is a table lookup times a power of two, so
         * there is no rounding anywhere and anything but a bit-exact match is a bug */
        int bad = 0; double worst = 0.0; int at = -1;
        for (int i = 0; i < ne_; i++) {
            const double d = fabs((double)y[i] - (double)ef[i]);
            if (d > worst) { worst = d; at = i; }
            if (d != 0.0) bad++;
        }
        if (bad == 0) {
            printf("  PASS  mxfp4          %d rows x %d elems, EXACT on released checkpoint bytes\n",
                   rows, pcols * 2);
            g_pass++;
        } else {
            printf("  FAIL  mxfp4          %d of %d elements differ, worst %.7g at %d "
                   "(got %.7f want %.7f)\n", bad, ne_, worst, at, y[at], ef[at]);
            g_fail++;
        }
        free(P); free(S); free(y);
    }
    free(pf); free(sf); free(ef); free(txt); free(ar);
}

/* k3_matmul_bf16 must equal k3_matmul EXACTLY, not approximately.
 *
 * Both widen the same bf16 values to the same float32 values (a left shift by 16, which
 * is lossless), then accumulate in double in the same order with the same four partial
 * sums. So the only way they can differ is if one of them is wrong. Comparing with a
 * tolerance here would hide precisely the bugs worth catching: a wrong stride, a
 * dropped tail element, a mis-shifted widen.
 *
 * This test needs no fixture. It generates bf16 bit patterns directly, which also means
 * it covers values a Gaussian sample would never produce - the checkpoint contains
 * denormals and very large exponents, and the widen must handle them by construction
 * rather than by luck.
 */
static void t_matmul_bf16(void)
{
    const int in = 257, out = 129;            /* deliberately not multiples of 4 */
    uint16_t *Wb = (uint16_t *)malloc((size_t)in * out * sizeof(uint16_t));
    float    *Wf = (float *)malloc((size_t)in * out * sizeof(float));
    float    *x  = (float *)malloc((size_t)in * sizeof(float));
    float    *ya = (float *)malloc((size_t)out * sizeof(float));
    float    *yb = (float *)malloc((size_t)out * sizeof(float));
    if (!Wb || !Wf || !x || !ya || !yb) { printf("  FAIL  matmul_bf16 (alloc)\n"); g_fail++; return; }

    unsigned s = 0xC0FFEEu;
    for (size_t i = 0; i < (size_t)in * out; i++) {
        s ^= s << 13; s ^= s >> 17; s ^= s << 5;
        /* Any 16-bit pattern EXCEPT the NaN/Inf exponent, which would make every
         * comparison trivially NaN and prove nothing. */
        uint16_t h = (uint16_t)(s >> 8);
        if (((h >> 7) & 0xFF) == 0xFF) h &= 0x7F7Fu;
        Wb[i] = h;
        Wf[i] = k3_bf16f(h);                  /* the SAME value, stored wide */
    }
    for (int i = 0; i < in; i++) {
        s ^= s << 13; s ^= s >> 17; s ^= s << 5;
        x[i] = (float)(s >> 8) / 8388608.0f - 1.0f;
    }

    k3_matmul(ya, x, Wf, in, out);
    k3_matmul_bf16(yb, x, Wb, in, out);

    int bad = 0;
    for (int o = 0; o < out; o++) {
        union { float f; uint32_t u; } a, b;
        a.f = ya[o]; b.f = yb[o];
        if (a.u != b.u) bad++;
    }
    if (bad) { printf("  FAIL  matmul_bf16   %d/%d rows differ from the fp32 path\n", bad, out); g_fail++; }
    else     { printf("  PASS  matmul_bf16   n=%d    bit-identical to k3_matmul\n", out); g_pass++; }
    free(Wb); free(Wf); free(x); free(ya); free(yb);
}

/* The batched trunk matmul must equal the per-position kernels BIT FOR BIT.
 *
 * k3_matmul_bf16_batch and k3_matmul_batch exist so that prefill and speculative
 * verification read and widen each trunk matrix once for T positions instead of T times.
 * Their whole claim is that no output moves: the same operands, accumulator partition,
 * fma order, reduction tree and tail as k3_matmul_bf16 / k3_matmul on one position. So the
 * comparison is on bits, over shapes chosen to reach every branch -- in below, at and
 * above one 16-element chunk and every in % 16 remainder that matters, out below and
 * above the OpenMP threshold, position counts that fill 1, 2 and 3 register blocks of
 * every width the build may pick (K3_MM_TB: 2 on NEON, 4 on AVX2, 8 with AVX-512VL) and
 * leave every remainder after them -- 1 to 7 for a block of 8, which takes a block of 4
 * before its last 1 to 3 -- and an `in` wide enough that the positions are split into
 * several passes over the matrix, including a final pass of one. Weights are arbitrary finite
 * bf16 bit patterns (denormals and huge exponents included); activations mix signs,
 * zeros, denormals and wide magnitudes. The strided forms are checked to write exactly
 * their rows and nothing between them, and k3_mmw_batch is checked through every weight
 * tag, including a streamed matrix with and without an apply_batch callback. */
static unsigned g_rng = 0x5EEDu;
static unsigned rnd(void) { g_rng ^= g_rng << 13; g_rng ^= g_rng >> 17; g_rng ^= g_rng << 5; return g_rng; }

static float rnd_x(void)
{
    const unsigned r = rnd();
    switch (r & 15u) {
    case 0:  return 0.0f;
    case 1:  return -0.0f;
    case 2:  return (float)((int)(r >> 8) - 8388608) * 1e-44f;   /* denormal range */
    case 3:  return (float)((int)(r >> 8) - 8388608) * 1e-3f;    /* up to ~8e3     */
    default: return (float)(r >> 8) / 8388608.0f - 1.0f;
    }
}

static uint16_t rnd_bf16(void)
{
    uint16_t h = (uint16_t)(rnd() >> 8);
    if (((h >> 7) & 0xFF) == 0xFF) h &= 0x7F7Fu;   /* finite only; NaN proves nothing */
    return h;
}

/* CANCELLING operands, the ones that make a wrong summation order VISIBLE.
 *
 * With ordinary values a reassociated double sum differs from the right one in its last
 * bit or two, and the final rounding to float erases that almost every time: measured, a
 * kernel with a deliberately wrong reduction tree passed thousands of random cases. Wide
 * random magnitudes do not help either, because the largest terms dominate every order
 * alike. What exposes the order is exact cancellation: each row carries one product of
 * +2^60*v and one of -2^60*v (same activation v, opposite weights) on top of ordinary
 * terms. The exact sum is just the ordinary terms, but in double every ordinary term that
 * meets the 2^60 partial sum BEFORE the two cancel is absorbed and lost, and which terms
 * those are is decided precisely by the accumulator partition, the order within each
 * accumulator, the reduction tree and the tail. Get any of them wrong and the float result
 * changes outright. The pair's slots are drawn per row from a few indices shared by the
 * matrix, since v must be the same in both slots for every position. */
static uint16_t bf16_of(float f) { uint32_t u; memcpy(&u, &f, 4); return (uint16_t)(u >> 16); }

static void fill_cancelling(uint16_t *Wb, float *Wf, float *X, int in, int out, int T, int ldx)
{
    int big[4], nbig = in < 4 ? in : 4;
    for (int k = 0; k < nbig; k++) {
        int dup;
        do {
            big[k] = (int)(rnd() % (unsigned)in);
            dup = 0;
            for (int m = 0; m < k; m++) if (big[m] == big[k]) dup = 1;
        } while (dup);
    }
    for (int t = 0; t < T; t++) {
        float *xt = X + (size_t)t * ldx;
        for (int i = 0; i < ldx; i++) xt[i] = (float)(rnd() >> 8) / 8388608.0f - 1.0f;
        const float v = ((rnd() & 1u) ? -1.0f : 1.0f) * (1.0f + (float)(rnd() & 0xFFu) / 256.0f);
        for (int k = 0; k < nbig; k++) xt[big[k]] = v;
    }
    for (int o = 0; o < out; o++) {
        uint16_t *wb = Wb + (size_t)o * in;
        float    *wf = Wf + (size_t)o * in;
        for (int i = 0; i < in; i++) {
            const uint16_t h = bf16_of((float)(rnd() >> 8) / 8388608.0f - 1.0f);
            wb[i] = h; wf[i] = k3_bf16f(h);
        }
        if (nbig < 2) continue;
        for (int k = 0; k < nbig; k++) { wb[big[k]] = 0; wf[big[k]] = 0.0f; }
        const int p = (int)(rnd() % (unsigned)nbig);
        int q = (int)(rnd() % (unsigned)(nbig - 1));
        if (q >= p) q++;
        wb[big[p]] = 0x5D80u; wf[big[p]] = k3_bf16f(0x5D80u);    /* +2^60 */
        wb[big[q]] = 0xDD80u; wf[big[q]] = k3_bf16f(0xDD80u);    /* -2^60 */
    }
}

typedef struct {
    K3WeightStream s;
    const uint16_t *W;
    int calls, batch_calls, rows_calls;
} MockStream;
static void mock_apply(const K3WeightStream *s, float *y, const float *x, int in, int out)
{
    MockStream *m = (MockStream *)(void *)s;
    m->calls++;
    k3_matmul_bf16(y, x, m->W, in, out);
}
static void mock_apply_rows(const K3WeightStream *s, float *y, const float *x, int in,
                            int out, int blk, int r0, int nr)
{
    MockStream *m = (MockStream *)(void *)s;
    m->rows_calls++;
    k3_matmul_bf16_rows(y, x, m->W, in, out, blk, r0, nr);
}
static void mock_apply_batch(const K3WeightStream *s, float *Y, int ldy, const float *X,
                             int ldx, int in, int out, int T)
{
    MockStream *m = (MockStream *)(void *)s;
    m->batch_calls++;
    k3_matmul_bf16_batch_ld(Y, ldy, X, ldx, m->W, in, out, T);
}

static int same_bits(const float *a, const float *b, size_t n)
{
    return memcmp(a, b, n * sizeof(float)) == 0;
}

static void t_matmul_batch(void)
{
    static const int ins[]  = {1, 5, 15, 16, 17, 31, 32, 33, 47, 100, 257, 1000};
    static const int outs[] = {1, 3, 64, 65, 129, 300};
    static const int Ts[]   = {1, 2, 3, 4, 5, 6, 7, 8, 15, 17, 26};
    const int nin = (int)(sizeof ins / sizeof *ins), nout = (int)(sizeof outs / sizeof *outs);
    const int nT = (int)(sizeof Ts / sizeof *Ts);
    long cases = 0, bad = 0;
    char where[160] = "";

    for (int a = 0; a <= nin; a++) {
        /* the last "in" is wide enough that 17 positions take several passes */
        const int in = a < nin ? ins[a] : 33000;
        for (int b = 0; b < nout; b++) {
            const int out = a < nin ? outs[b] : 70;
            if (a == nin && b > 0) break;
            for (int c = 0; c < nT; c++) {
                const int T = Ts[c];
                const int ldx = in + 5, ldy = out + 3;
                const size_t nw = (size_t)in * out;
                uint16_t *Wb = (uint16_t *)malloc(nw * sizeof(uint16_t));
                float *Wf = (float *)malloc(nw * sizeof(float));
                float *X  = (float *)malloc((size_t)T * ldx * sizeof(float));
                float *Yr = (float *)malloc((size_t)T * ldy * sizeof(float));
                float *Yb = (float *)malloc((size_t)T * ldy * sizeof(float));
                if (!Wb || !Wf || !X || !Yr || !Yb) {
                    printf("  FAIL  matmul_batch   allocation\n"); g_fail++;
                    free(Wb); free(Wf); free(X); free(Yr); free(Yb); return;
                }
                /* odd cases draw arbitrary values, even cases cancelling ones */
                if ((a + b + c) % 2 == 0) {
                    fill_cancelling(Wb, Wf, X, in, out, T, ldx);
                } else {
                    for (size_t i = 0; i < nw; i++) { Wb[i] = rnd_bf16(); Wf[i] = rnd_x(); }
                    for (size_t i = 0; i < (size_t)T * ldx; i++) X[i] = rnd_x();
                }

                for (int dt = 0; dt < 2; dt++) {
                    /* reference: the single-position kernel, one position at a time */
                    for (int t = 0; t < T; t++) {
                        if (dt) k3_matmul_bf16(Yr + (size_t)t * out, X + (size_t)t * ldx,
                                               Wb, in, out);
                        else    k3_matmul(Yr + (size_t)t * out, X + (size_t)t * ldx,
                                          Wf, in, out);
                    }
                    /* dense form, from a compact copy of X */
                    float *Xc = (float *)malloc((size_t)T * in * sizeof(float));
                    for (int t = 0; t < T; t++)
                        memcpy(Xc + (size_t)t * in, X + (size_t)t * ldx, (size_t)in * sizeof(float));
                    for (size_t i = 0; i < (size_t)T * ldy; i++) Yb[i] = -12345.0f;
                    if (dt) k3_matmul_bf16_batch(Yb, Xc, Wb, in, out, T);
                    else    k3_matmul_batch(Yb, Xc, Wf, in, out, T);
                    cases++;
                    if (!same_bits(Yr, Yb, (size_t)T * out)) {
                        bad++;
                        snprintf(where, sizeof where, "%s dense in=%d out=%d T=%d",
                                 dt ? "bf16" : "fp32", in, out, T);
                    }
                    /* strided form: rows land at ldy, gaps untouched */
                    for (size_t i = 0; i < (size_t)T * ldy; i++) Yb[i] = -12345.0f;
                    if (dt) k3_matmul_bf16_batch_ld(Yb, ldy, X, ldx, Wb, in, out, T);
                    else    k3_matmul_batch_ld(Yb, ldy, X, ldx, Wf, in, out, T);
                    cases++;
                    int ok = 1;
                    for (int t = 0; t < T && ok; t++) {
                        if (!same_bits(Yr + (size_t)t * out, Yb + (size_t)t * ldy, (size_t)out)) ok = 0;
                        for (int g = out; g < ldy; g++)
                            if (Yb[(size_t)t * ldy + g] != -12345.0f) ok = 0;
                    }
                    if (!ok) {
                        bad++;
                        snprintf(where, sizeof where, "%s strided in=%d out=%d T=%d",
                                 dt ? "bf16" : "fp32", in, out, T);
                    }
                    /* the dispatcher, through the tag that selects this kernel */
                    for (size_t i = 0; i < (size_t)T * ldy; i++) Yb[i] = -12345.0f;
                    k3_mmw_batch(Yb, Xc, dt ? (const void *)Wb : (const void *)Wf,
                                 dt ? K3_WBF16 : K3_WF32, in, out, T);
                    cases++;
                    if (!same_bits(Yr, Yb, (size_t)T * out)) {
                        bad++;
                        snprintf(where, sizeof where, "%s k3_mmw_batch in=%d out=%d T=%d",
                                 dt ? "bf16" : "fp32", in, out, T);
                    }
                    free(Xc);
                }

                /* a streamed matrix: apply_batch when present, per-position apply when not */
                if (in <= 257) {
                    for (int with_batch = 0; with_batch < 2; with_batch++) {
                        MockStream ms; memset(&ms, 0, sizeof ms);
                        ms.s.apply = mock_apply;
                        ms.s.apply_batch = with_batch ? mock_apply_batch : NULL;
                        ms.W = Wb;
                        for (int t = 0; t < T; t++)
                            k3_matmul_bf16(Yr + (size_t)t * out, X + (size_t)t * ldx, Wb, in, out);
                        for (size_t i = 0; i < (size_t)T * ldy; i++) Yb[i] = -12345.0f;
                        k3_mmw_batch_ld(Yb, ldy, X, ldx, &ms, K3_WSTREAM, in, out, T);
                        cases++;
                        int ok = 1;
                        for (int t = 0; t < T; t++)
                            if (!same_bits(Yr + (size_t)t * out, Yb + (size_t)t * ldy, (size_t)out)) ok = 0;
                        /* T == 1 must take the single-position path; otherwise one batch
                         * call when the callback exists, T calls of apply when it does not */
                        const int want_batch = (with_batch && T > 1) ? 1 : 0;
                        const int want_calls = want_batch ? 0 : T;
                        if (ms.batch_calls != want_batch || ms.calls != want_calls) ok = 0;
                        if (!ok) {
                            bad++;
                            snprintf(where, sizeof where, "stream%s in=%d out=%d T=%d calls=%d/%d",
                                     with_batch ? "+batch" : "", in, out, T, ms.calls, ms.batch_calls);
                        }
                    }
                }
                free(Wb); free(Wf); free(X); free(Yr); free(Yb);
            }
        }
    }

    /* NaN OUTPUTS. The per-position kernels store every NaN as the one quiet NaN
     * 0x7FC00000 (k3_out_f32 in k3_ops.c), because which input NaN an operation passes
     * on is not fixed by IEEE 754 and differs between instruction sequences. The
     * batched tiles are other instruction sequences again, so a NaN they produce must be
     * stored the same way or a prefill and a decode of the same position disagree in
     * the NaN's sign and payload. The finite draws above cannot see this, so here each
     * position's x and each row's weights carry NaNs of random sign and payload, in the
     * whole chunks and in the tail, plus an infinite x beside a zero weight (0 * inf is
     * the default NaN), and positions differ in which rows go NaN. */
    {
        static const int nins[] = {17, 33, 100};
        static const int nouts[] = {3, 65};
        static const int nTs[] = {2, 3, 5, 8, 9, 17};
        long nan_outputs = 0;
        for (int a = 0; a < 3; a++)
            for (int b = 0; b < 2; b++)
                for (int c = 0; c < 6; c++) {
                    const int in = nins[a], out = nouts[b], T = nTs[c];
                    const size_t nw = (size_t)in * out;
                    uint16_t *Wb = (uint16_t *)malloc(nw * sizeof(uint16_t));
                    float *Wf = (float *)malloc(nw * sizeof(float));
                    float *X  = (float *)malloc((size_t)T * in * sizeof(float));
                    float *Yr = (float *)malloc((size_t)T * out * sizeof(float));
                    float *Yb = (float *)malloc((size_t)T * out * sizeof(float));
                    if (!Wb || !Wf || !X || !Yr || !Yb) {
                        bad++; snprintf(where, sizeof where, "nan allocation");
                        free(Wb); free(Wf); free(X); free(Yr); free(Yb); continue;
                    }
                    for (size_t i = 0; i < nw; i++) { Wb[i] = rnd_bf16(); Wf[i] = rnd_x(); }
                    for (size_t i = 0; i < (size_t)T * in; i++) X[i] = rnd_x();
                    for (int o = 0; o < out; o++) {
                        if (rnd() % 3u == 0) continue;                  /* some rows stay finite */
                        for (int k = 1 + (int)(rnd() % 3u); k > 0; k--) {
                            const int at = (int)(rnd() % (unsigned)in);
                            const uint32_t u = 0x7FC00000u | (rnd() & 0x803FFFFFu);
                            float f; memcpy(&f, &u, 4);
                            Wf[(size_t)o * in + at] = f;
                            Wb[(size_t)o * in + at] = (uint16_t)(u >> 16);
                        }
                    }
                    for (int t = 0; t < T; t++) {
                        if (rnd() % 4u == 0) {                          /* one NaN x: all rows */
                            const uint32_t u = 0x7FC00000u | (rnd() & 0x803FFFFFu);
                            memcpy(&X[(size_t)t * in + rnd() % (unsigned)in], &u, 4);
                        } else if (rnd() % 3u == 0) {                   /* 0 * inf in row 0 */
                            const int at = (int)(rnd() % (unsigned)in);
                            X[(size_t)t * in + at] = (rnd() & 1u) ? INFINITY : -INFINITY;
                            Wb[at] = 0; Wf[at] = 0.0f;
                        }
                    }
                    for (int dt = 0; dt < 2; dt++) {
                        for (int t = 0; t < T; t++) {
                            if (dt) k3_matmul_bf16(Yr + (size_t)t * out, X + (size_t)t * in,
                                                   Wb, in, out);
                            else    k3_matmul(Yr + (size_t)t * out, X + (size_t)t * in,
                                              Wf, in, out);
                        }
                        if (dt) k3_matmul_bf16_batch(Yb, X, Wb, in, out, T);
                        else    k3_matmul_batch(Yb, X, Wf, in, out, T);
                        cases++;
                        for (size_t i = 0; i < (size_t)T * out; i++) nan_outputs += Yr[i] != Yr[i];
                        if (!same_bits(Yr, Yb, (size_t)T * out)) {
                            bad++;
                            snprintf(where, sizeof where, "%s NaN in=%d out=%d T=%d",
                                     dt ? "bf16" : "fp32", in, out, T);
                        }
                    }
                    free(Wb); free(Wf); free(X); free(Yr); free(Yb);
                }
        if (nan_outputs == 0) {                           /* the check must see some NaN */
            bad++; snprintf(where, sizeof where, "NaN cases produced no NaN output");
        }
    }

    /* K3_WI8 carries no exactness contract; the dispatcher must simply be the per-position
     * draft kernel, so it is compared to exactly that. */
    {
        const int in = 100, out = 70, T = 5;
        const size_t rowb = (size_t)4 + (size_t)in;
        unsigned char *W8 = (unsigned char *)malloc(rowb * out);
        float *X  = (float *)malloc((size_t)T * in * sizeof(float));
        float *Yr = (float *)malloc((size_t)T * out * sizeof(float));
        float *Yb = (float *)malloc((size_t)T * out * sizeof(float));
        for (int o = 0; o < out; o++) {
            const float sc = 0.01f * (float)(o + 1);
            memcpy(W8 + (size_t)o * rowb, &sc, 4);
            for (int i = 0; i < in; i++) W8[(size_t)o * rowb + 4 + i] = (unsigned char)rnd();
        }
        for (int i = 0; i < T * in; i++) X[i] = rnd_x();
        for (int t = 0; t < T; t++)
            k3_matmul_q8(Yr + (size_t)t * out, X + (size_t)t * in, W8, in, out);
        k3_mmw_batch(Yb, X, W8, K3_WI8, in, out, T);
        cases++;
        if (!same_bits(Yr, Yb, (size_t)T * out)) { bad++; snprintf(where, sizeof where, "int8 draft"); }
        free(W8); free(X); free(Yr); free(Yb);
    }

    if (bad) {
        printf("  FAIL  matmul_batch   %ld/%ld cases differ from the per-position kernels, "
               "e.g. %s\n", bad, cases, where);
        g_fail++;
    } else {
        printf("  PASS  matmul_batch   %ld cases, T in {1..8,15,17,26}, bit-identical to "
               "per-position k3_matmul_bf16 / k3_matmul\n", cases);
        g_pass++;
    }
}

/* A SELECTION of rows must be the full kernels' rows BIT FOR BIT, and nothing else.
 *
 * k3_matmul_rows, k3_matmul_bf16_rows and k3_matmul_q8_rows compute rows r0 .. r0 + nr - 1
 * of every block of blk rows (the --kv-latent path applies kv_b's key rows to score and
 * its value rows to weight). Their claim is that a row is the same float whichever rows
 * the call computes, and that a row nobody selected is not written. So each case fills
 * the output with a sentinel, runs a selection, and compares every selected row with the
 * full kernel's bits and every other row with the sentinel: through each kernel directly
 * and through k3_mmw_rows under every weight tag, including a streamed matrix with
 * apply_rows (one call, the selection only) and without it (apply, every row; the
 * contract then leaves the rest unspecified, and they are the full kernel's rows).
 * Selections cover a single block, many blocks, runs that start mid-block and end at
 * the block's end, one row per block, an odd number of rows in all (the bf16 kernel's
 * last pair is one row) and in a run (a pair then spans two blocks), counts below and
 * above the OpenMP threshold, the fixture's and K3's kv_b head layouts, and every
 * in % 16 tail that matters; half the cases use cancelling operands, where a row summed
 * in any other order changes its float, and one set carries NaNs. An empty selection
 * must write nothing, and where the platform can fork, a selection that names rows
 * outside the matrix must abort before writing anything (see refuses_selection). */
#ifndef _WIN32
/* Run one row-selection kernel (0 fp32, 1 bf16, 2 int8) on a selection in a child
 * process and report whether it aborted. The buffers are large and the pointers sit in
 * their middle, so a kernel that skipped its check would still stay inside them on the
 * selections used here and return: an abort can then only be the check's, even under
 * ASan, whose report on a stray write would also end in abort(). */
static int refuses_selection(int kernel, int out, int blk, int r0, int nr)
{
    enum { IN = 16, ROWS = 256 };
    static float y[2 * ROWS], x[IN], wf[2 * ROWS * IN];
    static uint16_t wb[2 * ROWS * IN];
    static unsigned char w8[2 * ROWS * (4 + IN)];
    fflush(stdout);
    fflush(stderr);
    const pid_t pid = fork();
    if (pid < 0) return 0;
    if (pid == 0) {
        if (!freopen("/dev/null", "w", stderr)) _exit(3);   /* the FATAL message */
        if (kernel == 0)
            k3_matmul_rows(y + ROWS, x, wf + ROWS * IN, IN, out, blk, r0, nr);
        else if (kernel == 1)
            k3_matmul_bf16_rows(y + ROWS, x, wb + ROWS * IN, IN, out, blk, r0, nr);
        else
            k3_matmul_q8_rows(y + ROWS, x, w8 + ROWS * (4 + IN), IN, out, blk, r0, nr);
        _exit(0);                                          /* returned: not refused */
    }
    int st = 0;
    if (waitpid(pid, &st, 0) != pid) return 0;
    return WIFSIGNALED(st) && WTERMSIG(st) == SIGABRT;
}
#endif

static void t_matmul_rows(void)
{
    static const int ins[] = {1, 5, 16, 17, 33, 100, 257};
    /* {out, blk, r0, nr} */
    static const int sel[][4] = {
        {7, 7, 0, 7},       /* one block, every row: the full product */
        {24, 8, 0, 5},      /* three blocks, a run at the start of each, odd total */
        {24, 8, 5, 3},      /* the rest of each block, runs ending at the block's end */
        {30, 10, 3, 3},     /* runs mid-block, a pair spanning two blocks */
        {160, 40, 0, 24},   /* the fixture's kv_b: 4 heads, keys (qk_nope 24) */
        {160, 40, 24, 16},  /* ... and values (v_head 16) */
        {70, 1, 0, 1},      /* one row per block, 70 selected: above the threshold */
        {287, 41, 7, 1},    /* one row per block, seven blocks */
        {130, 65, 1, 64},   /* 128 selected: over the threshold, pairs across blocks */
        {512, 256, 0, 128}, /* K3's kv_b head layout, two heads: keys */
        {512, 256, 128, 128}/* ... and values */
    };
    const int nin = (int)(sizeof ins / sizeof *ins), nsel = (int)(sizeof sel / sizeof *sel);
    const float SENT = -12345.0f;
    long cases = 0, bad = 0;
    char where[200] = "";

    for (int a = 0; a < nin; a++)
        for (int b = 0; b < nsel; b++) {
            const int in = ins[a], out = sel[b][0], blk = sel[b][1], r0 = sel[b][2];
            const int nr = sel[b][3];
            const size_t nw = (size_t)in * out, rowb = (size_t)4 + (size_t)in;
            uint16_t *Wb = (uint16_t *)malloc(nw * sizeof(uint16_t));
            float *Wf = (float *)malloc(nw * sizeof(float));
            unsigned char *W8 = (unsigned char *)malloc(rowb * out);
            float *x  = (float *)malloc((size_t)in * sizeof(float));
            float *Yr = (float *)malloc((size_t)out * sizeof(float));
            float *Ys = (float *)malloc((size_t)out * sizeof(float));
            if (!Wb || !Wf || !W8 || !x || !Yr || !Ys) {
                printf("  FAIL  matmul_rows    allocation\n"); g_fail++;
                free(Wb); free(Wf); free(W8); free(x); free(Yr); free(Ys); return;
            }
            if ((a + b) % 2 == 0) {
                fill_cancelling(Wb, Wf, x, in, out, 1, in);
            } else {
                for (size_t i = 0; i < nw; i++) { Wb[i] = rnd_bf16(); Wf[i] = rnd_x(); }
                for (int i = 0; i < in; i++) x[i] = rnd_x();
            }
            if (a == 3 && b % 3 == 0)                          /* NaNs in some rows */
                for (int o = 0; o < out; o += 3) {
                    const uint32_t u = 0x7FC00000u | (rnd() & 0x803FFFFFu);
                    float f; memcpy(&f, &u, 4);
                    const int at = (int)(rnd() % (unsigned)in);
                    Wf[(size_t)o * in + at] = f;
                    Wb[(size_t)o * in + at] = (uint16_t)(u >> 16);
                }
            for (int o = 0; o < out; o++) {
                const float sc = 0.01f * (float)(o % 13 + 1);
                memcpy(W8 + (size_t)o * rowb, &sc, 4);
                for (int i = 0; i < in; i++) W8[(size_t)o * rowb + 4 + i] = (unsigned char)rnd();
            }
            /* ks: the tag under test. 0 fp32, 1 bf16, 2 int8, each directly and through
             * k3_mmw_rows; 3 a stream with apply_rows, 4 a stream without it. */
            for (int ks = 0; ks < 5; ks++)
                for (int via = 0; via < (ks < 3 ? 2 : 1); via++) {
                    if (ks == 0)      k3_matmul(Yr, x, Wf, in, out);
                    else if (ks == 2) k3_matmul_q8(Yr, x, W8, in, out);
                    else              k3_matmul_bf16(Yr, x, Wb, in, out);
                    for (int o = 0; o < out; o++) Ys[o] = SENT;
                    MockStream ms; memset(&ms, 0, sizeof ms);
                    ms.s.apply = mock_apply;
                    ms.s.apply_rows = ks == 3 ? mock_apply_rows : NULL;
                    ms.W = Wb;
                    if (ks == 0 && !via)      k3_matmul_rows(Ys, x, Wf, in, out, blk, r0, nr);
                    else if (ks == 1 && !via) k3_matmul_bf16_rows(Ys, x, Wb, in, out, blk, r0, nr);
                    else if (ks == 2 && !via) k3_matmul_q8_rows(Ys, x, W8, in, out, blk, r0, nr);
                    else if (ks < 3)
                        k3_mmw_rows(Ys, x, ks == 0 ? (const void *)Wf
                                           : ks == 1 ? (const void *)Wb : (const void *)W8,
                                    ks == 0 ? K3_WF32 : ks == 1 ? K3_WBF16 : K3_WI8,
                                    in, out, blk, r0, nr);
                    else k3_mmw_rows(Ys, x, &ms, K3_WSTREAM, in, out, blk, r0, nr);
                    cases++;
                    int ok = 1;
                    for (int o = 0; o < out; o++) {
                        const int i = o % blk, picked = i >= r0 && i < r0 + nr;
                        if (picked || ks == 4) { if (!same_bits(Yr + o, Ys + o, 1)) ok = 0; }
                        else if (Ys[o] != SENT) ok = 0;
                    }
                    if (ks == 3 && (ms.rows_calls != 1 || ms.calls != 0)) ok = 0;
                    if (ks == 4 && (ms.rows_calls != 0 || ms.calls != 1)) ok = 0;
                    if (!ok) {
                        bad++;
                        snprintf(where, sizeof where, "%s%s in=%d out=%d blk=%d r0=%d nr=%d",
                                 (const char *[]){"fp32", "bf16", "int8", "stream+rows",
                                                  "stream"}[ks],
                                 via ? " via k3_mmw_rows" : "", in, out, blk, r0, nr);
                    }
                }
            free(Wb); free(Wf); free(W8); free(x); free(Yr); free(Ys);
        }

    /* Selecting no rows writes nothing: each of the three kernels, and k3_mmw_rows under
     * the fp32, bf16 and int8 tags and for a stream with apply_rows (a stream without it
     * computes every row, which k3_mmw_rows's contract allows). */
    {
        float y[4] = {SENT, SENT, SENT, SENT}, x[3] = {1.0f, 2.0f, 3.0f};
        const float wf[12] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
        const uint16_t wb[12] = {0x3F80, 0x4000, 0x4040, 0x4080, 0x40A0, 0x40C0,
                                 0x40E0, 0x4100, 0x4110, 0x4120, 0x4130, 0x4140};
        unsigned char w8[4 * 7];
        for (int o = 0; o < 4; o++) {
            const float sc = 0.5f;
            memcpy(w8 + o * 7, &sc, 4);
            for (int i = 0; i < 3; i++) w8[o * 7 + 4 + i] = (unsigned char)(o + i + 1);
        }
        MockStream ms; memset(&ms, 0, sizeof ms);
        ms.s.apply = mock_apply;
        ms.s.apply_rows = mock_apply_rows;
        ms.W = wb;
        k3_matmul_rows(y, x, wf, 3, 4, 2, 1, 0);
        k3_matmul_bf16_rows(y, x, wb, 3, 4, 2, 1, 0);
        k3_matmul_q8_rows(y, x, w8, 3, 4, 2, 1, 0);
        k3_mmw_rows(y, x, wf, K3_WF32, 3, 4, 2, 1, 0);
        k3_mmw_rows(y, x, wb, K3_WBF16, 3, 4, 2, 1, 0);
        k3_mmw_rows(y, x, w8, K3_WI8, 3, 4, 2, 1, 0);
        k3_mmw_rows(y, x, &ms, K3_WSTREAM, 3, 4, 2, 1, 0);
        cases++;
        int ok = ms.rows_calls == 1 && ms.calls == 0;
        for (int o = 0; o < 4; o++) ok &= y[o] == SENT;
        if (!ok) { bad++; snprintf(where, sizeof where, "empty selection"); }
    }

#ifndef _WIN32
    /* A selection that names rows outside the matrix aborts, in each kernel, before it
     * writes: a run past the block's end (rows 5..9 of blocks of 8, which unchecked writes
     * y[24] and y[25] of a 24-row matrix), a block that does not divide the rows, a
     * negative start, a zero block and a negative count. The valid edges (a run ending at
     * the block's end, an empty selection) are the cases above. */
    {
        static const int badsel[][4] = {{24, 8, 5, 5}, {24, 7, 0, 3}, {24, 8, -1, 2},
                                        {24, 0, 0, 1}, {24, 8, 0, -1}};
        for (int k = 0; k < 3; k++)
            for (size_t i = 0; i < sizeof badsel / sizeof *badsel; i++) {
                cases++;
                if (!refuses_selection(k, badsel[i][0], badsel[i][1], badsel[i][2],
                                       badsel[i][3])) {
                    bad++;
                    snprintf(where, sizeof where, "%s accepted out=%d blk=%d r0=%d nr=%d",
                             k == 0 ? "k3_matmul_rows" : k == 1 ? "k3_matmul_bf16_rows"
                                                                : "k3_matmul_q8_rows",
                             badsel[i][0], badsel[i][1], badsel[i][2], badsel[i][3]);
                }
            }
    }
#endif

    if (bad) {
        printf("  FAIL  matmul_rows    %ld/%ld cases differ from the full kernels, wrote "
               "an unselected row or accepted a bad selection, e.g. %s\n", bad, cases,
               where);
        g_fail++;
    } else {
#ifndef _WIN32
        const char *also = ", bad selections abort";
#else
        const char *also = "";                       /* no fork: not checked here */
#endif
        printf("  PASS  matmul_rows    %ld cases, selected rows bit-identical to the full "
               "kernels under every tag, no other row written%s\n", cases, also);
        g_pass++;
    }
}

int main(int argc, char **argv)
{
    const char *dir = (argc > 1) ? argv[1] : "../fixtures/ops";
    printf("Kimi K3 C ops, validated against the pure-torch reference\n");
    printf("fixtures: %s\n", dir);

    /* The manifest is the contract. Take its tolerances rather than hardcoded ones, and say out
     * loud which ones are in force so a future loosening cannot happen silently. */
    {
        char mp[512]; snprintf(mp, sizeof mp, "%s/MANIFEST.json", dir);
        char *mtxt = slurp_quiet(mp);
        if (!mtxt) {
            printf("tolerance: MANIFEST.json ABSENT, falling back to atol=%.1e rtol=%.1e\n\n",
                   (double)ATOL, (double)RTOL);
            g_skip++;
        } else {
            char *mar = NULL; jval *m = json_parse(mtxt, &mar);
            jval *tolo = m ? json_get(m, "tolerance") : NULL;
            const double fa = tolo ? num(tolo, "fp32_abs", ATOL) : ATOL;
            const double fr = tolo ? num(tolo, "fp32_rel", RTOL) : RTOL;
            ATOL = (float)fa; RTOL = (float)fr;
            printf("tolerance: atol=%.1e rtol=%.1e  (from MANIFEST.json)\n\n", fa, fr);
            free(mtxt); free(mar);
        }
    }

    t_rmsnorm(dir);
    t_situ(dir);
    t_shortconv(dir);
    t_decay(dir);
    t_recur(dir, "kda_recur1");
    t_recur(dir, "kda_recur8");
    t_router(dir);
    t_mla(dir);
    t_moe(dir);
    t_moe_prefill();
    t_mxfp4(dir);
    t_matmul_bf16();
    t_matmul_batch();
    t_matmul_rows();
    t_kda_layer(dir, "kda_layer1");
    t_kda_layer(dir, "kda_layer8");
    t_layer(dir, "layer_kda");
    t_layer(dir, "layer_mla");
    t_attnres(dir);

    printf("\n%d passed, %d failed, %d skipped\n", g_pass, g_fail, g_skip);
    if (g_skip)
        printf("SUITE INCOMPLETE: %d test(s) did not run. A skip is not a pass.\n", g_skip);
    return (g_fail || g_skip) ? 1 : 0;
}
